Repository boutproject/BOUT-dev, pull requests merged in 2018-03, with the labels that each got.

#911 Fix use of old `restarting` in slepc solver
  src/solver/impls/slepc-3.4/slepc-3.4.cxx
Labels: bugfix

#827 fix sign error in FDDX_U1
  include/bout_types.hxx
  src/mesh/index_derivs.cxx
Labels: bug

#828 Petsc3.7 compatibility
  configure
  configure.ac
Labels: in progress

#902 Replace new with array
  include/bout/globalfield.hxx
  include/bout/rkscheme.hxx
  src/field/globalfield.cxx
  src/invert/laplace/impls/multigrid/multigrid_alg.cxx
  src/invert/laplace/impls/multigrid/multigrid_laplace.cxx
  src/invert/laplace/impls/multigrid/multigrid_laplace.hxx
  src/invert/laplace/impls/multigrid/multigrid_solver.cxx
  src/invert/laplace/impls/mumps/mumps_laplace.cxx
  src/invert/laplace/impls/mumps/mumps_laplace.hxx
  src/invert/laplace/impls/shoot/shoot_laplace.cxx
  src/invert/laplace/impls/shoot/shoot_laplace.hxx
  src/mesh/data/gridfromfile.cxx
  src/mesh/impls/bout/boutmesh.cxx
  src/mesh/impls/bout/boutmesh.hxx
  src/solver/impls/euler/euler.cxx
  src/solver/impls/euler/euler.hxx
  src/solver/impls/imex-bdf2/imex-bdf2.cxx
  src/solver/impls/karniadakis/karniadakis.cxx
  src/solver/impls/karniadakis/karniadakis.hxx
  src/solver/impls/power/power.cxx
  src/solver/impls/power/power.hxx
  src/solver/impls/rk3-ssp/rk3-ssp.cxx
  src/solver/impls/rk3-ssp/rk3-ssp.hxx
  src/solver/impls/rk4/rk4.cxx
  src/solver/impls/rk4/rk4.hxx
  src/solver/impls/rkgeneric/impls/rk4simple/rk4simple.cxx
  src/solver/impls/rkgeneric/impls/rk4simple/rk4simple.hxx
  src/solver/impls/rkgeneric/rkgeneric.cxx
  src/solver/impls/rkgeneric/rkgeneric.hxx
  src/solver/impls/rkgeneric/rkscheme.cxx
  src/solver/impls/slepc-3.4/slepc-3.4.cxx
  src/solver/impls/slepc-3.4/slepc-3.4.hxx
Labels: discussion, in progress

#936 Speed up Travis and refactor config
  .install_miniconda_for_travis.sh
  .pip_install_for_travis.sh
  .travis.yml
  .travis_script.sh
Labels: performance

#927 Allow runtime control of maximum size of contiguous block to use in Region
  examples/performance/tuning_regionblocksize/data/BOUT.inp
  examples/performance/tuning_regionblocksize/makefile
  examples/performance/tuning_regionblocksize/run.sh
  examples/performance/tuning_regionblocksize/tuning_regionblocksize.cxx
  include/bout/mesh.hxx
  include/bout/region.hxx
  src/mesh/mesh.cxx
  tests/unit/test_extras.hxx
Labels: feature

#948 Extend differencing type checking slightly to be more rigorous in checking
  src/mesh/index_derivs.cxx
  tests/MMS/wave-1d-y/data/BOUT.inp
  tests/MMS/wave-1d/data/BOUT.inp
Labels: feature

#958 Catch all exceptions by reference
  examples/non-local_1d/non-local_1d.cxx
  src/invert/laplace/invert_laplace.cxx
  src/solver/impls/arkode/arkode.cxx
  src/solver/impls/cvode/cvode.cxx
  tests/integrated/test-multigrid_laplace/test_multigrid_laplace.cxx
  tests/integrated/test-petsc_laplace/test_petsc_laplace.cxx
  tests/integrated/test-petsc_laplace_MAST-grid/test_petsc_laplace_MAST_grid.cxx
Labels: bugfix

#962 Fix order of HDF5 flags
  configure
  m4/ax_lib_hdf5.m4
  m4/ax_lib_parallelhdf5.m4
Labels: bugfix
