Repository boutproject/BOUT-dev, pull requests merged in 2018-02, with the labels that each got.

#867 Bug fix for build without checks
  include/field2d.hxx
  include/field3d.hxx
Labels: bug

#872 Fix two potential bugs: out-of-bounds access and use-after-scope
  include/bout/array.hxx
  include/bout/region.hxx
Labels: bugfix

#871 Invalidate guards
  include/field2d.hxx
  include/field3d.hxx
  src/field/field2d.cxx
  src/field/field3d.cxx
  tests/integrated/test-drift-instability/BOUT.inp
  tests/integrated/test-fci-slab/data/BOUT.inp
  tests/integrated/test-fci-slab/mms/BOUT.inp
  tests/integrated/test-fieldgroupComm/cyclone_68x32.nc
  tests/integrated/test-gyro/data/BOUT.inp
  tests/integrated/test-interchange-instability/2fluid.cxx
  tests/integrated/test-interchange-instability/data_1/BOUT.inp
  tests/integrated/test-interchange-instability/data_10/BOUT.inp
  tests/integrated/test-laplace/data/BOUT.inp
  tests/unit/field/test_field2d.cxx
  tests/unit/field/test_field3d.cxx
Labels: feature

#878 Better matrices/tensors
  include/bout/coordinates.hxx
  include/bout/rkscheme.hxx
  include/interpolation.hxx
  include/mask.hxx
  include/utils.hxx
  src/mesh/coordinates.cxx
  src/mesh/interpolation/bilinear.cxx
  src/mesh/interpolation/hermite_spline.cxx
  src/mesh/interpolation/lagrange_4pt.cxx
  src/mesh/parallel/fci.cxx
  src/physics/smoothing.cxx
  src/solver/impls/rkgeneric/impls/cashkarp/cashkarp.cxx
  src/solver/impls/rkgeneric/impls/rk4simple/rk4simple.cxx
  src/solver/impls/rkgeneric/impls/rkf34/rkf34.cxx
  src/solver/impls/rkgeneric/impls/rkf45/rkf45.cxx
  src/solver/impls/rkgeneric/rkgeneric.cxx
  src/solver/impls/rkgeneric/rkscheme.cxx
  tests/unit/sys/test_utils.cxx
Labels: feature

#875 Extend Region class
  examples/performance/iterator/iterator.cxx
  include/bout/region.hxx
  include/field2d.hxx
  src/field/field2d.cxx
  tests/unit/field/test_field2d.cxx
  tests/unit/field/test_field3d.cxx
  tests/unit/include/bout/test_region.cxx
  tests/unit/mesh/test_mesh.cxx
  tests/unit/mesh/test_region.cxx
Labels: feature
