Repository boutproject/BOUT-dev, pull requests merged in 2018-12, with the labels that each got.

#1410 Add some missing autoconf macros needed to build configure
  README.md
  m4/ax_append_compile_flags.m4
  m4/ax_append_flag.m4
  m4/ax_check_compile_flag.m4
  m4/ax_require_defined.m4
Labels: bugfix

#1421 Fix failure of collect() with integer slice argument
  tools/pylib/boutdata/collect.py
Labels: bugfix

#1438 Be more explicit about how many threads to use in some tests.
  tests/integrated/test-cyclic/runtest
  tests/integrated/test-delp2/runtest
  tests/integrated/test-fci-slab/runtest
  tests/integrated/test-invpar/runtest
  tests/integrated/test-laplace/runtest
Labels: performance

#1440 Removes explicit request for timezone
  src/sys/utils.cxx
Labels: work in progress

#1434 Fix FV::Div_par_K_Grad_par
  src/mesh/fv_ops.cxx
Labels: bugfix

#1439 Add tool for generic operator inversion
  examples/invertable_operator/.gitignore
  examples/invertable_operator/data/BOUT.inp
  examples/invertable_operator/invertable_operator.cxx
  examples/invertable_operator/makefile
  include/bout/invertable_operator.hxx
  include/bout/mesh.hxx
  manual/sphinx/user_docs/invertable_operator.rst
  src/mesh/mesh.cxx
  tests/integrated/test-invertable-operator/.gitignore
  tests/integrated/test-invertable-operator/data/BOUT.inp
  tests/integrated/test-invertable-operator/invertable_operator.cxx
  tests/integrated/test-invertable-operator/makefile
  tests/integrated/test-invertable-operator/runtest
Labels: feature

#1446 Pass f_aligned to standardDerivative in DDY/D2DY2/D4DY4
  include/bout/index_derivs_interface.hxx
  tests/integrated/test-yupdown/runtest
  tests/integrated/test-yupdown/test_yupdown.cxx
Labels: bugfix

#1462 Use function local storage in shiftZ rather than member storage
  include/bout/paralleltransform.hxx
  src/mesh/parallel/shiftedmetric.cxx
Labels: bugfix

#1441 Add FieldPerp location
  include/field.hxx
  include/fieldperp.hxx
  src/field/field3d.cxx
  src/field/fieldperp.cxx
  src/invert/laplace/impls/cyclic/cyclic_laplace.cxx
  src/invert/laplace/impls/multigrid/multigrid_laplace.cxx
  src/invert/laplace/impls/multigrid/multigrid_laplace.hxx
  src/invert/laplace/impls/mumps/mumps_laplace.cxx
  src/invert/laplace/impls/pdd/pdd.cxx
  src/invert/laplace/impls/petsc/petsc_laplace.cxx
  src/invert/laplace/impls/serial_band/serial_band.cxx
  src/invert/laplace/impls/serial_tri/serial_tri.cxx
  src/invert/laplace/impls/shoot/shoot_laplace.cxx
  src/invert/laplace/impls/spt/spt.cxx
  src/invert/laplace/invert_laplace.cxx
  src/mesh/difops.cxx
  tests/unit/field/test_fieldperp.cxx
Labels: feature, work in progress
