Repository boutproject/BOUT-dev, pull requests merged in 2018-07, with the labels that each got.

#1139 Restore coordinate documentation
  manual/sphinx/index.rst
  manual/sphinx/user_docs/BOUT_Gradperp_op.rst
  manual/sphinx/user_docs/coordinates.rst
  manual/sphinx/user_docs/preconditioning.rst
Labels: documentation

#1180 Expose applyBoundary to boutcore
  tools/pylib/_boutcore_build/boutcore.pyx.in
  tools/pylib/_boutcore_build/boutcpp.pxd.in
Labels: PythonInterface

#1172 Fix documentation
  include/bout/surfaceiter.hxx
Labels: documentation, easyfix

#1168 Add support for multiple Options
  tests/MMS/bracket/runtest
  tests/MMS/derivatives3/runtest
  tests/integrated/test-boutcore/mms-ddz/runtest
  tools/pylib/_boutcore_build/boutcore.pyx.in
  tools/pylib/_boutcore_build/boutcpp.pxd.in
Labels: PythonInterface

#1188 Escape variable names for expression parsing in BoutOptions/BoutOptionsFile
  tools/pylib/boutdata/data.py
Labels: bugfix

#1184 Manual operator typo
  manual/sphinx/user_docs/algebraic_operators.rst
Labels: documentation
