Repository boutproject/BOUT-dev, pull requests merged in 2018-11, with the labels that each got.

#1351 BoundaryOp refactor performance regression fix?
  examples/BoundaryOp_timing/BoundaryOp_timing.cxx
  examples/BoundaryOp_timing/data/BOUT.inp
  examples/BoundaryOp_timing/makefile
  include/boundary_op.hxx
  include/boundary_standard.hxx
  src/mesh/boundary_op.cxx
  src/mesh/boundary_standard.cxx
Labels: discussion, work in progress

#1374 Check for nullptr in NcFormat::get/setAttribute
  src/fileio/impls/netcdf/nc_format.cxx
Labels: bugfix

#1373 Print command line options to output_info
  src/bout++.cxx
Labels: feature

#1379 Fix:Escaping in makefile
  tools/pylib/_boutcore_build/Makefile
Labels: bugfix

#1387 Hypnotoad: fix unstable integration method used to calculate zShift
  tools/idllib/int_trapezoid.pro
  tools/idllib/surface_average.pro
  tools/tokamak_grids/gridgen/adjust_jpar.pro
  tools/tokamak_grids/gridgen/create_grid.pro
  tools/tokamak_grids/gridgen/create_nonorthogonal.pro
  tools/tokamak_grids/gridgen/gridgen.pro
  tools/tokamak_grids/gridgen/hypnotoad.pro
  tools/tokamak_grids/gridgen/interp_smooth.pro
  tools/tokamak_grids/gridgen/process_grid.pro
  tools/tokamak_grids/gridgen/run_test.pro
  tools/tokamak_grids/gridgen/test.pro
Labels: bugfix

#1390 Replace abs with std abs
  include/cyclic_reduction.hxx
  include/utils.hxx
  src/field/fieldgenerators.cxx
  src/solver/impls/imex-bdf2/imex-bdf2.cxx
  src/solver/impls/rkgeneric/rkscheme.cxx
  src/solver/impls/slepc/slepc.cxx
Labels: bugfix

#1382 Don't clobber command line short options when reading input file
  src/bout++.cxx
  tests/integrated/test-command-args/runtest
Labels: bugfix

#1388 Fix examples so most compile
  examples/2Dturbulence_multigrid/esel.cxx
  examples/6field-simple/elm_6f.cxx
  examples/advdiff/advdiff.cxx
  examples/advdiff2/init.cxx
  examples/conducting-wall-mode/cwm.cxx
  examples/dalf3/dalf3.cxx
  examples/elm-pb/elm_pb.cxx
  examples/em-drift/2fluid.cxx
  examples/fci-wave-logn/fci-wave.cxx
  examples/fci-wave/fci-wave.cxx
  examples/gas-compress/gas_compress.cxx
  examples/gravity_reduced/gravity_reduced.cxx
  examples/gyro-gem/gem.cxx
  examples/jorek-compare/jorek_compare.cxx
  examples/lapd-drift/lapd_drift.cxx
  examples/non-local_1d/cubic_spline_local.hxx
  examples/reconnect-2field/2field.cxx
  examples/shear-alfven-wave/2fluid.cxx
  examples/subsampling/monitor.cxx
  examples/uedge-benchmark/data/BOUT.inp
  examples/uedge-benchmark/ue_bmark.cxx
  examples/wave-slab/wave_slab.cxx
  include/difops.hxx
Labels: bugfix

#1399 More fixes for invparderiv
  include/invert_parderiv.hxx
  src/invert/parderiv/impls/cyclic/cyclic.cxx
  src/invert/parderiv/impls/cyclic/cyclic.hxx
  src/invert/parderiv/impls/makefile
  src/invert/parderiv/impls/serial/makefile
  src/invert/parderiv/impls/serial/serial.cxx
  src/invert/parderiv/impls/serial/serial.hxx
  src/invert/parderiv/parderiv_factory.cxx
Labels: bugfix

#1398 Fix setCoefs in InvertPar
  include/invert_parderiv.hxx
  tests/integrated/test-invpar/runtest
  tests/integrated/test-invpar/test_invpar.cxx
Labels: bugfix

#1401 Bugfix: new_location check in setLocation would always be false
  src/field/field2d.cxx
  src/field/field3d.cxx
Labels: bugfix

#1409 Fix MAYBE_UNUSED for some compilers
  include/unused.hxx
Labels: bugfix
