Repository boutproject/BOUT-dev, pull requests merged in 2018-04, with the labels that each got.

#964 Fix assignment in assert
  src/mesh/difops.cxx
Labels: bugfix

#1000 Avoid exception if no implementation found
  tools/pylib/boututils/datafile.py
Labels: easyfix

#935 Remove copy on write from matrix/tensor
  include/utils.hxx
Labels: performance

#960 Ensure nullptr checks come before dereferences
  src/mesh/impls/bout/boutmesh.cxx
  src/mesh/mesh.cxx
  src/solver/solver.cxx
  src/sys/comm_group.cxx
  tests/unit/mesh/test_boutmesh.cxx
Labels: bugfix

#934 Fieldops region 2d-3d special treatment
  include/bout/mesh.hxx
  include/bout/region.hxx
  src/field/field2d.cxx
  src/field/gen_fieldops.jinja
  src/field/gen_fieldops.py
  src/field/generated_fieldops.cxx
  src/mesh/mesh.cxx
  tests/unit/include/bout/test_region.cxx
  tests/unit/mesh/test_mesh.cxx
  tests/unit/test_extras.hxx
Labels: performance

#1019 Even more manual improvements
  include/bout/fieldgroup.hxx
  include/bout/mesh.hxx
  include/bout/solver.hxx
  include/derivs.hxx
  include/derivs.hxx.in.jinja
  include/derivs.hxx.in.py
  include/field2d.hxx
  include/field3d.hxx
  include/fieldperp.hxx
  include/gyro_average.hxx
  include/msg_stack.hxx
  include/utils.hxx
  manual/sphinx/developer_docs/code_layout.rst
  manual/sphinx/user_docs/advanced_install.rst
  manual/sphinx/user_docs/bout_options.rst
  manual/sphinx/user_docs/input_grids.rst
  manual/sphinx/user_docs/running_bout.rst
  src/fileio/impls/netcdf4/ncxx4.cxx
  src/fileio/impls/netcdf4/ncxx4.hxx
  src/invert/laplace/impls/pdd/pdd.cxx
  src/invert/laplace/impls/serial_tri/serial_tri.cxx
  src/invert/laplace/impls/spt/spt.cxx
  src/makefile
  src/physics/gyro_average.cxx
  src/precon/makefile
  src/sys/timer.cxx
Labels: documentation

#980 Basic version of test requirement scripts
  bin/bout-config.in
  manual/sphinx/user_docs/testing.rst
  tests/README.md
  tests/integrated/makefile
  tests/integrated/test-code-style/runtest
  tests/integrated/test-fieldgroup/runtest
  tests/integrated/test-include/runtest
  tests/integrated/test-initial/runtest
  tests/integrated/test-multigrid_laplace/runtest
  tests/integrated/test-subdir/data/BOUT.inp
  tests/integrated/test_suite
  tests/integrated/test_suite_list
  tests/integrated/test_suite_make
  tests/requirements/__init__.py
  tests/requirements/mpich
  tests/requirements/requirements.py
  tests/requirements/travis
Labels: tests
