Repository boutproject/BOUT-dev, pull requests merged in 2018-09, with the labels that each got.

#1250 Respect 'enabled' option in Datafile::add
  src/fileio/datafile.cxx
Labels: bugfix

#1262 Less confusing error message
  tools/pylib/boutdata/collect.py
Labels: bugfix

#1244 Monitor frequency fix
  include/bout/physicsmodel.hxx
  manual/sphinx/user_docs/time_integration.rst
  src/physics/physicsmodel.cxx
  src/solver/solver.cxx
Labels: bugfix, documentation

#1251 Field2D and Coordinates for boutcore
  tools/pylib/_boutcore_build/GENERATION.md
  tools/pylib/_boutcore_build/boutcore.pyx.in
  tools/pylib/_boutcore_build/boutcpp.pxd.in
  tools/pylib/_boutcore_build/helper.cxx.in
  tools/pylib/_boutcore_build/helper.h.in
Labels: feature
