Repository boutproject/BOUT-dev, pull requests merged in 2019-05, with the labels that each got.

#1702 Allow default value of Options to be set from another Options object
  include/options.hxx
  manual/sphinx/user_docs/bout_options.rst
  tests/unit/sys/test_options.cxx
Labels: feature, small-change

#1707 Fixes for FV::Div_a_Laplace_perp
  src/mesh/fv_ops.cxx
Labels: bugfix, small-change

#1703 Do not calculate parallel slices for field-aligned fields
  include/bout/index_derivs_interface.hxx
  src/mesh/parallel/identity.cxx
  src/mesh/parallel/shiftedmetric.cxx
Labels: bugfix, small-change

#1704 Set y-direction of FieldPerp results in ParallelTransformIdentity
  include/bout/paralleltransform.hxx
  tests/unit/mesh/test_paralleltransform.cxx
Labels: bugfix, small-change

#1699 Fieldperp I/O
  include/bout/griddata.hxx
  include/bout/mesh.hxx
  include/bout_types.hxx
  include/datafile.hxx
  include/dataformat.hxx
  include/field.hxx
  include/field_factory.hxx
  manual/sphinx/developer_docs/file_io.rst
  src/field/field_factory.cxx
  src/fileio/datafile.cxx
  src/fileio/dataformat.cxx
  src/fileio/impls/hdf5/h5_format.cxx
  src/fileio/impls/hdf5/h5_format.hxx
  src/fileio/impls/netcdf/nc_format.cxx
  src/fileio/impls/netcdf/nc_format.hxx
  src/fileio/impls/netcdf4/ncxx4.cxx
  src/fileio/impls/netcdf4/ncxx4.hxx
  src/mesh/data/gridfromfile.cxx
  src/mesh/data/gridfromoptions.cxx
  src/mesh/impls/bout/boutmesh.hxx
  src/mesh/mesh.cxx
  src/sys/bout_types.cxx
  tests/integrated/test-io/data/benchmark.out.0.nc
  tests/integrated/test-io/generate.py
  tests/integrated/test-io/runtest
  tests/integrated/test-io/test_io.cxx
  tests/integrated/test-io/test_io.grd.nc
  tests/integrated/test-io_hdf5/data/benchmark.out.0.hdf5
  tests/integrated/test-io_hdf5/generate.py
  tests/integrated/test-io_hdf5/runtest
  tests/integrated/test-io_hdf5/test_io.cxx
  tests/integrated/test-io_hdf5/test_io.grd.hdf5
  tests/integrated/test-restart-io/.gitignore
  tests/integrated/test-restart-io/data/BOUT.inp
  tests/integrated/test-restart-io/makefile
  tests/integrated/test-restart-io/runtest
  tests/integrated/test-restart-io/test-restart-io.cxx
  tests/integrated/test-restart-io_hdf5/.gitignore
  tests/integrated/test-restart-io_hdf5/data/BOUT.inp
  tests/integrated/test-restart-io_hdf5/makefile
  tests/integrated/test-restart-io_hdf5/runtest
  tests/integrated/test-restart-io_hdf5/test-restart-io.cxx
  tests/unit/mesh/data/test_gridfromoptions.cxx
  tests/unit/mesh/test_boutmesh.cxx
  tests/unit/test_extras.hxx
  tools/pylib/boutdata/collect.py
  tools/pylib/boutdata/restart.py
  tools/pylib/boututils/datafile.py
Labels: feature

#1688 Fix elm pb example
  examples/elm-pb/data/BOUT.inp
  examples/elm-pb/elm_pb.cxx
Labels: bugfix

#1673 Runge-Kutta-Legendre stabilised explicit method
  examples/IMEX/advection-diffusion/README.md
  examples/IMEX/advection-diffusion/data/BOUT.inp
  examples/IMEX/advection-diffusion/imex.cxx
  examples/IMEX/diffusion-nl/diffusion-nl.cxx
  examples/IMEX/drift-wave/test-drift.cxx
  include/bout/solver.hxx
  manual/sphinx/user_docs/time_integration.rst
  src/solver/impls/makefile
  src/solver/impls/split-rk/README.md
  src/solver/impls/split-rk/makefile
  src/solver/impls/split-rk/split-rk.cxx
  src/solver/impls/split-rk/split-rk.hxx
  src/solver/solver.cxx
  src/solver/solverfactory.cxx
  tests/MMS/time/runtest
  tests/MMS/time/time.cxx
  tests/integrated/test-solver/data/BOUT.inp
Labels: feature

#1712 Tidy up direction-type setters
  include/field.hxx
  include/field2d.hxx
  include/field3d.hxx
  include/fieldperp.hxx
Labels: small-change

#1727 Deprecate Karniadakis solver
  src/solver/impls/karniadakis/karniadakis.cxx
Labels: small-change

#1661 Make mixed second-derivative operators more correct
  include/derivs.hxx
  manual/sphinx/user_docs/differential_operators.rst
  src/sys/derivs.cxx
Labels: bugfix

#1741 Correct calculation of Bxy when interpolating from CELL_CENTRE
  src/mesh/coordinates.cxx
Labels: bugfix, small-change

#1739 Only call checkPositive(g) for grid cells
  src/mesh/coordinates.cxx
Labels: bugfix, small-change
