Repository boutproject/BOUT-dev, pull requests merged in 2019-04, with the labels that each got.

#1658 Counters for timers, makes them correct with multiple Timer objects
  include/bout/sys/timer.hxx
  src/sys/timer.cxx
  tests/unit/sys/test_timer.cxx
Labels: bugfix, small-change

#1635 Make ParallelTransform location-aware
  include/bout/coordinates.hxx
  include/bout/fv_ops.hxx
  include/bout/index_derivs_interface.hxx
  include/bout/mesh.hxx
  include/bout/paralleltransform.hxx
  include/field2d.hxx
  include/field3d.hxx
  include/interpolation.hxx
  src/bout++.cxx
  src/field/field3d.cxx
  src/field/field_factory.cxx
  src/fileio/datafile.cxx
  src/invert/parderiv/impls/cyclic/cyclic.cxx
  src/mesh/boundary_standard.cxx
  src/mesh/coordinates.cxx
  src/mesh/difops.cxx
  src/mesh/fv_ops.cxx
  src/mesh/impls/bout/boutmesh.cxx
  src/mesh/impls/bout/boutmesh.hxx
  src/mesh/mesh.cxx
  src/mesh/parallel/fci.cxx
  src/mesh/parallel/fci.hxx
  src/mesh/parallel/identity.cxx
  src/mesh/parallel/shiftedmetric.cxx
  src/physics/smoothing.cxx
  tests/integrated/test-smooth/test_smooth.cxx
  tests/integrated/test-yupdown/data/BOUT.inp
  tests/integrated/test-yupdown/test_yupdown.cxx
  tests/unit/field/test_field3d.cxx
  tests/unit/field/test_field_factory.cxx
  tests/unit/field/test_initialprofiles.cxx
  tests/unit/include/test_derivs.cxx
  tests/unit/mesh/data/test_gridfromoptions.cxx
  tests/unit/mesh/parallel/test_shiftedmetric.cxx
  tests/unit/mesh/test_interpolation.cxx
  tests/unit/mesh/test_paralleltransform.cxx
  tests/unit/test_extras.hxx
  tools/pylib/_boutcore_build/boutcore.pyx.in
  tools/pylib/_boutcore_build/boutcpp.pxd.in
Labels: feature

#1663 Bugfix: return fields by reference
  tools/pylib/_boutcore_build/boutcore.pyx.in
Labels: PythonInterface

#1670 Allow relative paths to be followed when making
  make.config.in
Labels: small-change

#1662 Allow clean exit in boutcore
  tests/integrated/test-boutcore/collect-staggered/runtest
  tests/integrated/test-boutcore/collect/runtest
  tests/integrated/test-boutcore/legacy-model/runtest
  tests/integrated/test-boutcore/mms-ddz/runtest
  tests/integrated/test-boutcore/simple-model/runtest
  tools/pylib/_boutcore_build/boutcore.pyx.in
Labels: PythonInterface

#1669 Method for Laplace solvers to say whether they use 3D coefficients
  include/invert_laplace.hxx
  src/invert/laplace/impls/multigrid/multigrid_laplace.hxx
  src/invert/laplace/impls/mumps/mumps_laplace.hxx
  src/invert/laplace/impls/naulin/naulin_laplace.hxx
Labels: small-change

#1653 Options type and doc attributes
  examples/2Dturbulence_multigrid/data/BOUT.inp
  examples/2Dturbulence_multigrid/esel.cxx
  examples/blob2d/blob2d.cxx
  examples/conducting-wall-mode/cwm.cxx
  examples/conduction/conduction.cxx
  examples/fci-wave/fci-wave.cxx
  examples/finite-volume/diffusion/diffusion.cxx
  examples/finite-volume/fluid/fluid.cxx
  examples/gas-compress/advect1d/BOUT.inp
  examples/gas-compress/gas_compress.cxx
  examples/hasegawa-wakatani/hw.cxx
  examples/orszag-tang/mhd.cxx
  examples/reconnect-2field/2field.cxx
  examples/reconnect-2field/data/BOUT.inp
  include/bout/sys/type_name.hxx
  include/field.hxx
  include/field2d.hxx
  include/field3d.hxx
  include/options.hxx
  include/options_netcdf.hxx
  manual/sphinx/user_docs/bout_options.rst
  manual/sphinx/user_docs/running_bout.rst
  src/bout++.cxx
  src/field/field2d.cxx
  src/field/field3d.cxx
  src/invert/fft_fftw.cxx
  src/invert/laplace/impls/petsc/petsc_laplace.cxx
  src/invert/laplace/invert_laplace.cxx
  src/invert/laplacexy/laplacexy.cxx
  src/invert/laplacexz/impls/petsc/laplacexz-petsc.cxx
  src/invert/laplacexz/laplacexz.cxx
  src/mesh/impls/bout/boutmesh.cxx
  src/mesh/interpolation/interpolation_factory.cxx
  src/mesh/mesh.cxx
  src/mesh/parallel/shiftedmetric.cxx
  src/solver/impls/cvode/cvode.cxx
  src/solver/impls/rk4/rk4.cxx
  src/solver/impls/rkgeneric/rkgeneric.cxx
  src/solver/solver.cxx
  src/sys/makefile
  src/sys/options.cxx
  src/sys/options/options_ini.cxx
  src/sys/options/options_netcdf.cxx
  src/sys/type_name.cxx
  tests/integrated/test-code-style/runtest
  tests/integrated/test-options-netcdf/test-options-netcdf.cxx
  tests/unit/sys/test_options.cxx
  tests/unit/sys/test_options_fields.cxx
  tests/unit/sys/test_options_netcdf.cxx
  tests/unit/sys/test_type_name.cxx
Labels: documentation, feature

#1674 Add .BOUT.pid.* files to .gitignore
  .gitignore
Labels: small-change

#1679 Ignore new meta-vars in test-squash
  bin/bout-squashoutput
  tests/integrated/test-squash/runtest
Labels: bugfix, small-change, tests

#1646 Fix y-boundaries of Coordinates fields
  include/bout/coordinates.hxx
  include/bout/griddata.hxx
  include/bout/mesh.hxx
  src/mesh/coordinates.cxx
  src/mesh/data/gridfromfile.cxx
  src/mesh/impls/bout/boutmesh.cxx
  src/mesh/mesh.cxx
  src/mesh/parallel/fci.cxx
  src/mesh/parallel/identity.cxx
  src/mesh/parallel/shiftedmetric.cxx
  tests/integrated/test-griddata-yboundary-guards/data-doublenull-0/BOUT.inp
  tests/integrated/test-griddata-yboundary-guards/data-doublenull-1/BOUT.inp
  tests/integrated/test-griddata-yboundary-guards/data-doublenull-2/BOUT.inp
  tests/integrated/test-griddata-yboundary-guards/data-singlenull-0/BOUT.inp
  tests/integrated/test-griddata-yboundary-guards/data-singlenull-1/BOUT.inp
  tests/integrated/test-griddata-yboundary-guards/data-singlenull-2/BOUT.inp
  tests/integrated/test-griddata-yboundary-guards/makefile
  tests/integrated/test-griddata-yboundary-guards/runtest
  tests/integrated/test-griddata-yboundary-guards/test_griddata.cxx
  tests/integrated/test-griddata/runtest
  tests/unit/mesh/test_boutmesh.cxx
  tests/unit/sys/test_options.cxx
  tools/idllib/file_write_string.pro
Labels: bugfix

#1683 call Finalise in test
  tests/integrated/test-datadir/test.cxx
Labels: bugfix, small-change, tests

#1682 Fix comparison of corner boundary cells in test-squash
  tests/integrated/test-squash/runtest
Labels: bugfix, small-change, tests

#1681 Clear Field3D parallel slices in operator=
  src/field/field3d.cxx
  src/field/gen_fieldops.jinja
  src/field/generated_fieldops.cxx
Labels: bugfix, small-change

#1684 Fix and reenable
  tests/MMS/advection/data/BOUT.inp
  tests/MMS/advection/weno3/runtest
Labels: bugfix, small-change, tests

#1689 Remove multiple printing of BOUTLOCALE to stderr
  src/bout++.cxx
Labels: small-change

#1686 Bugfix: bracket operator slowdown
  include/field3d.hxx
  src/field/field3d.cxx
  src/mesh/difops.cxx
Labels: bugfix, performance, small-change

#1692 Warn about random failures in test
  tests/integrated/test-coordinates-initialization/runtest
Labels: small-change, tests

#1691 Use asynchronous communications in LaplaceMultigrid
  src/invert/laplace/impls/multigrid/multigrid_alg.cxx
  src/invert/laplace/impls/multigrid/multigrid_laplace.cxx
Labels: performance

#1695 Convert Options::isSection() argument to lower case
  src/sys/options.cxx
  tests/unit/sys/test_options.cxx
Labels: bugfix, tests

#1697 Add support for shifting a FieldPerp toFieldAligned/fromFieldAligned
  include/bout/paralleltransform.hxx
  include/fieldperp.hxx
  src/field/fieldperp.cxx
  src/mesh/parallel/fci.hxx
  src/mesh/parallel/shiftedmetric.cxx
  tests/unit/mesh/parallel/test_shiftedmetric.cxx
Labels: feature

#1693 Move Gridfile::get implementations for Field3D/Field2D to .cxx
  include/bout/griddata.hxx
  src/mesh/data/gridfromfile.cxx
Labels: bugfix

#1698 Set y-direction of results in ParallelTransformIdentity
  include/bout/paralleltransform.hxx
  tests/unit/mesh/test_paralleltransform.cxx
Labels: bugfix, small-change
