Repository boutproject/BOUT-dev, pull requests merged in 2019-06, with the labels that each got.

#1725 Bugfix: use region in Coordinates::calcCovariant/calcContravariant
  .travis.yml
  include/bout/coordinates.hxx
  src/mesh/coordinates.cxx
  tests/integrated/test-laplace/data/BOUT.inp
  tests/integrated/test-laplace/runtest
  tests/unit/src/test_bout++.cxx
Labels: bugfix

#1736 Output ParallelTransform variables
  include/bout/paralleltransform.hxx
  src/mesh/coordinates.cxx
  src/mesh/parallel/shiftedmetric.cxx
Labels: small-change

#1745 Don't mark Coordinates::zShift as const, can't be output
  include/bout/paralleltransform.hxx
Labels: bugfix

#1744 Laplacian: FFT include dfdz term, plus manual updates
  manual/sphinx/user_docs/coordinates.rst
  manual/sphinx/user_docs/laplacian.rst
  src/invert/laplace/invert_laplace.cxx
Labels: documentation

#1746 Pin packages in requirements.txt for Sphinx docs
  manual/sphinx/requirements.txt
Labels: small-change

#1735 Fix BoutMesh decomposition on single processor
  src/mesh/impls/bout/boutmesh.cxx
  tests/unit/mesh/test_boutmesh.cxx
Labels: small-change

#1726 Make MsgStack and BoutException unit tests more flexible
  tests/unit/sys/test_boutexception.cxx
  tests/unit/sys/test_msg_stack.cxx
Labels: small-change

#1724 Hardcode all variables for test-solver; remove input file
  tests/integrated/test-solver/data/BOUT.inp
  tests/integrated/test-solver/test_solver.cxx
Labels: small-change

#1749 Bug fix, test and tidy SLEPc solver
  examples/eigen-box/README.md
  examples/eigen-box/data/BOUT.inp
  examples/eigen-box/eigen-box.cxx
  examples/eigen-box/eigenvals.py
  src/solver/impls/slepc/slepc.cxx
  tests/integrated/test-slepc-solver/.gitignore
  tests/integrated/test-slepc-solver/README.md
  tests/integrated/test-slepc-solver/data/BOUT.inp
  tests/integrated/test-slepc-solver/makefile
  tests/integrated/test-slepc-solver/runtest
  tests/integrated/test-slepc-solver/test-slepc-solver.cxx
Labels: bugfix

#1751 Build pdf manual
  manual/sphinx/conf.py
  manual/sphinx/user_docs/coordinates.rst
  manual/sphinx/user_docs/laplacian.rst
Labels: bugfix, documentation

#1752 Remove FIXME comment from interp_to
  include/interpolation.hxx
Labels: small-change
