Repository boutproject/BOUT-dev, pull requests merged in 2019-10, with the labels that each got.

#1800 Fix assignment instead of comparison in ASSERTs
  src/invert/laplace/impls/shoot/shoot_laplace.cxx
  src/invert/laplace/impls/spt/spt.cxx
  src/invert/laplace/invert_laplace.cxx
  src/mesh/boundary_standard.cxx
Labels: bugfix, small-change

#1801 Fix for Intel enabling -Wnull-dereference despite not accepting it
  configure
  configure.ac
Labels: small-change

#1796 Make CELL_LOC strongly typed
  include/boundary_region.hxx
  include/bout/griddata.hxx
  include/bout/solver.hxx
  include/bout_types.hxx
  include/difops.hxx
  include/parallel_boundary_op.hxx
  src/mesh/coordinates.cxx
  src/mesh/parallel_boundary_op.cxx
  src/solver/solver.cxx
  tests/MMS/derivatives3/runtest
  tests/MMS/upwinding3/runtest
  tools/pylib/_boutcore_build/boutcore.pyx.in
  tools/pylib/_boutcore_build/other_enums.hxx
  tools/pylib/_boutcore_build/resolve_enum.pxd.in
Labels: bugfix, proposal, small-change

#1799 Fix y-extrapolation in BoundaryDirichlet::apply(Field2D&)
  src/mesh/boundary_standard.cxx
Labels: bugfix, small-change

#1804 Remove some superfluous location checks in Laplacian
  src/invert/laplace/invert_laplace.cxx
Labels: bugfix, small-change

#1791 Fix initial conditions not being transformed correctly
  include/bout/index_derivs_interface.hxx
  src/field/field_factory.cxx
  src/mesh/parallel/shiftedmetric.cxx
  tests/MMS/spatial/fci/fci_mms.cxx
  tests/integrated/test-yupdown/test_yupdown.cxx
  tests/unit/field/test_field_factory.cxx
  tests/unit/mesh/parallel/test_shiftedmetric.cxx
Labels: bugfix

#1806 Bugfix: result of InvertParCR::solve tagged in wrong y space
  src/invert/parderiv/impls/cyclic/cyclic.cxx
Labels: bugfix, small-change

#1807 Bugfix: cyclic parallel derivative inversion done in wrong space
  src/invert/parderiv/impls/cyclic/cyclic.cxx
Labels: bugfix, small-change

#1815 Save all commonly used geometry variables
  src/mesh/coordinates.cxx
Labels: small-change

#1809 Bugfixes for writing Vector2D and Vector3D
  src/fileio/datafile.cxx
Labels: bugfix

#1813 Make interp_to and finite-volume parallel operators return result in the same space as the input
  include/bout/fv_ops.hxx
  include/bout/paralleltransform.hxx
  include/interpolation.hxx
  src/mesh/fv_ops.cxx
  tests/unit/mesh/test_interpolation.cxx
Labels: bugfix

#1817 Add counters to Timers to avoid double-counting sections
  include/bout/sys/timer.hxx
  src/sys/timer.cxx
Labels: bugfix, small-change

#1812 Ensure parallel_transform is only read from grid files, not from options
  include/bout/griddata.hxx
  include/bout/mesh.hxx
  src/mesh/data/gridfromfile.cxx
  src/mesh/mesh.cxx
  src/mesh/parallel/fci.cxx
  src/mesh/parallel/identity.cxx
  src/mesh/parallel/shiftedmetric.cxx
Labels: bugfix

#1786 Implement the INVERT_ZERO_DC flag in LaplaceCyclic
  src/invert/laplace/impls/cyclic/cyclic_laplace.cxx
Labels: bugfix, small-change

#1794 Allow NYPE to be given instead of NXPE in input files
  manual/sphinx/user_docs/bout_options.rst
  src/mesh/impls/bout/boutmesh.cxx
  tests/integrated/test-io/runtest
Labels: feature, tests

#1824 Micro optimise some common routines for v4.3.0-rc
  src/field/field3d.cxx
  src/field/gen_fieldops.jinja
  src/field/generated_fieldops.cxx
Labels: performance
