Repository boutproject/BOUT-dev, pull requests merged in 2019-02, with the labels that each got.

#1553 Update name of helper function
  tests/unit/include/test_derivs.cxx
Labels: bugfix

#1546 Fix bug in DST option for cyclic solve
  src/invert/laplace/impls/cyclic/cyclic_laplace.cxx
Labels: bugfix

#1561 Hypnotoad: handle case when break of contour is very close to x-point
  tools/tokamak_grids/gridgen/leg_separatrix2.pro
Labels: bugfix

#1562 Hypnotoad: add checkbox to output metrics for orthogonal coordinates
  tools/tokamak_grids/gridgen/hypnotoad.pro
  tools/tokamak_grids/gridgen/process_grid.pro
Labels: feature

#1563 Enable communications for simulations with no core, only divertor legs
  src/mesh/impls/bout/boutmesh.cxx
Labels: feature

#1558 Prevent data corruption
  src/bout++.cxx
  src/solver/solver.cxx
Labels: bugfix

#1574 Ensure Coordinates is a complete type when trying to swap
  include/bout/coordinates.hxx
  include/bout/mesh.hxx
  src/mesh/mesh.cxx
Labels: bugfix

#1575 Hypnotoad: output coordinate system labelling
  include/bout/griddata.hxx
  include/bout/mesh.hxx
  include/bout/paralleltransform.hxx
  src/mesh/data/gridfromfile.cxx
  src/mesh/data/gridfromoptions.cxx
  src/mesh/mesh.cxx
  src/mesh/parallel/fci.cxx
  src/mesh/parallel/fci.hxx
  src/mesh/parallel/identity.cxx
  src/mesh/parallel/shiftedmetric.cxx
  tests/unit/include/test_derivs.cxx
  tests/unit/mesh/test_boutmesh.cxx
  tests/unit/mesh/test_interpolation.cxx
  tests/unit/mesh/test_paralleltransform.cxx
  tools/idllib/file_write_string.pro
  tools/tokamak_grids/gridgen/process_grid.pro
Labels: feature, proposal

#1580 Provide argument for printf
  src/mesh/mesh.cxx
Labels: bugfix

#1585 use MPIRUN if set
  tests/integrated/test-vec/runtest
Labels: bugfix

#1586 Check buffer length
  src/sys/optionsreader.cxx
Labels: bugfix

#1581 More printf
  include/bout/format.hxx
  include/bout/sys/expressionparser.hxx
  include/boutexception.hxx
  include/datafile.hxx
  include/msg_stack.hxx
  include/optionsreader.hxx
  include/output.hxx
  src/field/fieldgenerators.cxx
  src/field/fieldgenerators.hxx
  src/mesh/data/gridfromfile.cxx
  src/mesh/impls/bout/boutmesh.cxx
  src/sys/expressionparser.cxx
  tools/pylib/_boutcore_build/boutcore.pyx.in
  tools/pylib/_boutcore_build/boutcpp.pxd.in
Labels: bugfix

#1583 Prevent failures on parallel, clean build
  src/makefile
Labels: bugfix

#1590 InterpolationFactory tests
  include/interpolation_factory.hxx
  tests/unit/include/test_interpolation_factory.cxx
  tests/unit/test_extras.hxx
Labels: tests

#1592 More unit tests for derivatives
  include/bout/deriv_store.hxx
  tests/unit/include/bout/test_deriv_store.cxx
  tests/unit/include/test_derivs.cxx
Labels: tests

#1593 Hypnotoad nonorthogonal fixes
  tools/tokamak_grids/gridgen/create_grid.pro
  tools/tokamak_grids/gridgen/create_nonorthogonal.pro
  tools/tokamak_grids/gridgen/follow_gradient_nonorth.pro
  tools/tokamak_grids/gridgen/leg_separatrix2.pro
Labels: bugfix

#1559 Inform about gettext's license
  README.md
Labels: documentation, question

#1595 Hypnotoad version numbering
  tools/idllib/file_write_attribute.pro
  tools/tokamak_grids/gridgen/hypnotoad_version.pro
  tools/tokamak_grids/gridgen/process_grid.pro
Labels: feature, proposal

#1591 More Field* tests
  examples/6field-simple/elm_6f.cxx
  examples/elm-pb/elm_pb.cxx
  include/field3d.hxx
  src/field/field3d.cxx
  tests/MMS/elm-pb/elm_pb.cxx
  tests/unit/bout_test_main.cxx
  tests/unit/field/test_field.cxx
  tests/unit/field/test_field2d.cxx
  tests/unit/field/test_field3d.cxx
  tests/unit/field/test_vector2d.cxx
  tests/unit/field/test_vector3d.cxx
  tests/unit/include/test_derivs.cxx
  tests/unit/invert/test_fft.cxx
  tests/unit/mesh/parallel/test_shiftedmetric.cxx
Labels: tests

#1605 Bugfix laplacexz
  include/bout/invert/laplacexy.hxx
  include/bout/invert/laplacexz.hxx
  src/mesh/mesh.cxx
Labels: bugfix

#1606 Fix FV::Div_a_Laplace_perp and FV::Div_par_K_Grad_par
  src/mesh/fv_ops.cxx
Labels: bugfix

#1609 Fix a couple of small(ish) bugs in FV::Div_par_K_Grad_par
  src/mesh/fv_ops.cxx
Labels: bugfix

#1611 Check if we need to link against libdl for dladdr
  configure
  configure.ac
Labels: bugfix, build-system
