Repository boutproject/BOUT-dev, pull requests merged in 2019-03, with the labels that each got.

#1613 A few small unit test improvements
  include/bout_types.hxx
  include/field_factory.hxx
  include/interpolation_factory.hxx
  src/mesh/interpolation/interpolation_factory.cxx
  tests/unit/bout_test_main.cxx
  tests/unit/field/test_field_factory.cxx
  tests/unit/include/bout/test_generic_factory.cxx
  tests/unit/include/test_interpolation_factory.cxx
  tests/unit/include/test_mask.cxx
Labels: tests

#1608 V4.2.2 Release Candidate
  CHANGELOG.md
  CITATION.bib
  CITATION.cff
  configure
  configure.ac
  include/mask.hxx
  include/output.hxx
  manual/doxygen/Doxyfile
  manual/doxygen/Doxyfile_readthedocs
  manual/sphinx/conf.py
  src/bout++.cxx
  src/fileio/impls/hdf5/h5_format.cxx
  src/mesh/coordinates.cxx
  src/mesh/fv_ops.cxx
  src/solver/impls/cvode/cvode.cxx
  src/solver/solver.cxx
  src/sys/output.cxx
Labels: release

#1615 Add FDDX_U2 implementation, plus minor bugfixes
  include/bout/deriv_store.hxx
  src/mesh/index_derivs.cxx
  src/sys/derivs.cxx
Labels: bugfix, feature

#1620 Fix printf formats in Ncxx4/H5Format::setAttribute(..., BoutReal)
  src/fileio/impls/hdf5/h5_format.cxx
  src/fileio/impls/netcdf4/ncxx4.cxx
Labels: bugfix

#1506 Two stage add coordinates
  include/bout/mesh.hxx
  src/field/field2d.cxx
  src/field/field3d.cxx
  src/field/fieldperp.cxx
  src/mesh/impls/bout/boutmesh.cxx
  tests/integrated/.gitignore
  tests/integrated/test-coordinates-initialization/README.md
  tests/integrated/test-coordinates-initialization/data/BOUT.inp
  tests/integrated/test-coordinates-initialization/makefile
  tests/integrated/test-coordinates-initialization/runtest
  tests/integrated/test-coordinates-initialization/test-coordinates-initialization.cxx
  tests/unit/field/test_field2d.cxx
  tests/unit/field/test_field3d.cxx
  tests/unit/field/test_field_factory.cxx
  tests/unit/field/test_fieldperp.cxx
  tests/unit/field/test_vector2d.cxx
  tests/unit/field/test_vector3d.cxx
  tests/unit/mesh/parallel/test_shiftedmetric.cxx
  tests/unit/mesh/test_interpolation.cxx
  tests/unit/test_extras.hxx
Labels: bugfix

#1626 Bug in calculation of ShiftAngle (qloop)
  tools/tokamak_grids/gridgen/hypnotoad_version.pro
  tools/tokamak_grids/gridgen/process_grid.pro
Labels: bugfix

#1589 Timer tests and refactor
  include/bout/sys/timer.hxx
  src/sys/timer.cxx
  tests/unit/sys/test_timer.cxx
Labels: tests

#1531 Write job execution information to dump file
  include/bout.hxx
  include/bout/monitor.hxx
  src/bout++.cxx
Labels: feature

#1624 Direction tagging and emptyFrom
  include/bout/fv_ops.hxx
  include/bout/index_derivs_interface.hxx
  include/bout/invertable_operator.hxx
  include/bout/mesh.hxx
  include/bout/paralleltransform.hxx
  include/bout_types.hxx
  include/field.hxx
  include/field2d.hxx
  include/field3d.hxx
  include/fieldperp.hxx
  include/interpolation.hxx
  src/field/field.cxx
  src/field/field2d.cxx
  src/field/field3d.cxx
  src/field/fieldperp.cxx
  src/field/gen_fieldops.jinja
  src/field/generated_fieldops.cxx
  src/field/vecops.cxx
  src/field/vector2d.cxx
  src/field/vector3d.cxx
  src/field/where.cxx
  src/fileio/datafile.cxx
  src/invert/laplace/impls/cyclic/cyclic_laplace.cxx
  src/invert/laplace/impls/multigrid/multigrid_laplace.cxx
  src/invert/laplace/impls/multigrid/multigrid_laplace.hxx
  src/invert/laplace/impls/naulin/naulin_laplace.hxx
  src/invert/laplace/impls/pdd/pdd.cxx
  src/invert/laplace/impls/serial_band/serial_band.cxx
  src/invert/laplace/impls/serial_tri/serial_tri.cxx
  src/invert/laplace/impls/shoot/shoot_laplace.cxx
  src/invert/laplace/impls/spt/spt.cxx
  src/invert/laplace/invert_laplace.cxx
  src/invert/laplacexz/impls/cyclic/laplacexz-cyclic.cxx
  src/invert/laplacexz/impls/petsc/laplacexz-petsc.cxx
  src/invert/parderiv/impls/cyclic/cyclic.cxx
  src/mesh/coordinates.cxx
  src/mesh/difops.cxx
  src/mesh/fv_ops.cxx
  src/mesh/impls/bout/boutmesh.cxx
  src/mesh/interpolation.cxx
  src/mesh/interpolation/bilinear.cxx
  src/mesh/interpolation/hermite_spline.cxx
  src/mesh/interpolation/lagrange_4pt.cxx
  src/mesh/mesh.cxx
  src/mesh/parallel/fci.cxx
  src/mesh/parallel/shiftedmetric.cxx
  src/physics/smoothing.cxx
  src/physics/sourcex.cxx
  src/solver/impls/petsc/petsc.cxx
  src/solver/solver.cxx
  src/sys/bout_types.cxx
  src/sys/derivs.cxx
  tests/unit/field/test_field.cxx
  tests/unit/field/test_field2d.cxx
  tests/unit/field/test_field3d.cxx
  tests/unit/field/test_fieldperp.cxx
  tests/unit/mesh/parallel/test_shiftedmetric.cxx
  tests/unit/test_extras.hxx
Labels: feature, proposal

#1632 Add EXTRA_LIBS to LIBS when searching for libraries
  configure
  m4/bout.m4
Labels: bugfix

#1423 Start to introduce zstart and zend
  include/bout/mesh.hxx
  src/mesh/difops.cxx
  src/mesh/impls/bout/boutmesh.cxx
  src/mesh/impls/bout/boutmesh.hxx
  src/mesh/mesh.cxx
  tests/MMS/bracket/runtest
  tests/unit/field/test_field3d.cxx
  tests/unit/test_extras.hxx
Labels: discussion, feature, work in progress

#1564 Allow Coordinates on staggered grids to be read from grid files
  include/bout/coordinates.hxx
  include/bout/mesh.hxx
  src/mesh/coordinates.cxx
  src/mesh/mesh.cxx
  tests/unit/field/test_field.cxx
  tests/unit/field/test_field2d.cxx
  tests/unit/field/test_field3d.cxx
  tests/unit/field/test_field_factory.cxx
  tests/unit/field/test_fieldperp.cxx
  tests/unit/field/test_vector2d.cxx
  tests/unit/field/test_vector3d.cxx
  tests/unit/include/test_derivs.cxx
  tests/unit/mesh/data/test_gridfromoptions.cxx
  tests/unit/mesh/parallel/test_shiftedmetric.cxx
  tests/unit/mesh/test_interpolation.cxx
  tests/unit/test_extras.hxx
Labels: feature

#1648 Make transforming Field3D inputs from field aligned optional
  include/field_factory.hxx
  manual/sphinx/user_docs/variable_init.rst
  src/field/field_factory.cxx
  tests/unit/field/test_field_factory.cxx
  tests/unit/field/test_vector3d.cxx
  tests/unit/sys/test_options_fields.cxx
Labels: small-change

#1650 Add name argument to Options::isSection to test for presence of subsection
  include/options.hxx
  src/sys/options.cxx
  tests/unit/sys/test_options.cxx
Labels: small-change

#1652 Fix mesh checks in Laplace implementation headers
  src/invert/laplace/impls/cyclic/cyclic_laplace.hxx
  src/invert/laplace/impls/multigrid/multigrid_laplace.hxx
  src/invert/laplace/impls/serial_band/serial_band.hxx
  src/invert/laplace/impls/serial_tri/serial_tri.hxx
  src/invert/laplace/impls/shoot/shoot_laplace.hxx
  src/invert/laplace/impls/spt/spt.hxx
Labels: bugfix, small-change

#1647 Hypnotoad: double precision and y-boundary guard cells
  tools/idllib/read_2d.pro
  tools/idllib/read_neqdsk.pro
  tools/tokamak_grids/gridgen/adjust_jpar.pro
  tools/tokamak_grids/gridgen/analyse_equil.pro
  tools/tokamak_grids/gridgen/bfield/dct2d.pro
  tools/tokamak_grids/gridgen/create_grid.pro
  tools/tokamak_grids/gridgen/create_nonorthogonal.pro
  tools/tokamak_grids/gridgen/curvature.pro
  tools/tokamak_grids/gridgen/dct.pro
  tools/tokamak_grids/gridgen/dct2d.pro
  tools/tokamak_grids/gridgen/dct2dslow.pro
  tools/tokamak_grids/gridgen/ddy.pro
  tools/tokamak_grids/gridgen/evalcosp.pro
  tools/tokamak_grids/gridgen/evalcospfast.pro
  tools/tokamak_grids/gridgen/flux_tube.pro
  tools/tokamak_grids/gridgen/follow_gradient.pro
  tools/tokamak_grids/gridgen/follow_gradient_nonorth.pro
  tools/tokamak_grids/gridgen/gen_surface_hypnotoad.pro
  tools/tokamak_grids/gridgen/get_line.pro
  tools/tokamak_grids/gridgen/get_line_nonorth.pro
  tools/tokamak_grids/gridgen/gridgen.pro
  tools/tokamak_grids/gridgen/hypnotoad.pro
  tools/tokamak_grids/gridgen/hypnotoad_version.pro
  tools/tokamak_grids/gridgen/int_y.pro
  tools/tokamak_grids/gridgen/leg_separatrix.pro
  tools/tokamak_grids/gridgen/leg_separatrix2.pro
  tools/tokamak_grids/gridgen/line_crossings.pro
  tools/tokamak_grids/gridgen/local_gradient.pro
  tools/tokamak_grids/gridgen/oplot_contour.pro
  tools/tokamak_grids/gridgen/oplot_critical.pro
  tools/tokamak_grids/gridgen/plot_mesh.pro
  tools/tokamak_grids/gridgen/plot_rz_equil.pro
  tools/tokamak_grids/gridgen/process_grid.pro
  tools/tokamak_grids/gridgen/prof_write.pro
  tools/tokamak_grids/gridgen/radial_grid.pro
  tools/tokamak_grids/gridgen/run_test.pro
  tools/tokamak_grids/gridgen/rz_curvature.pro
  tools/tokamak_grids/gridgen/smooth_nl.pro
  tools/tokamak_grids/gridgen/sol_flux_tube.pro
  tools/tokamak_grids/gridgen/test.pro
  tools/tokamak_grids/gridgen/theta_line.pro
Labels: auxiliary-tools, bugfix, feature
