Repository boutproject/BOUT-dev, pull requests merged in 2019-07, with the labels that each got.

#1757 Fix advection MMS tests
  tests/MMS/advection/advection.cxx
  tests/MMS/advection/runtest
  tests/MMS/spatial/advection/advection.cxx
  tests/MMS/spatial/advection/runtest
  tools/pylib/boututils/check_scaling.py
Labels: tests

#1748 SNB nonlocal heat flux model
  examples/conduction-snb/README.md
  examples/conduction-snb/conduction-snb.cxx
  examples/conduction-snb/data/BOUT.inp
  examples/conduction-snb/fit_temperature.py
  examples/conduction-snb/makefile
  examples/conduction-snb/sinusoid.py
  examples/conduction-snb/snb.csv
  examples/conduction-snb/spitzer-harm.csv
  examples/conduction-snb/step.py
  examples/conduction-snb/step/BOUT.inp
  examples/conduction-snb/temperature.csv
  examples/conduction-snb/vfp.csv
  include/bout/snb.hxx
  manual/sphinx/figs/snb-sinusoidal.png
  manual/sphinx/figs/snb-step.png
  manual/sphinx/index.rst
  manual/sphinx/user_docs/nonlocal.rst
  src/physics/makefile
  src/physics/snb.cxx
  tests/integrated/test-snb/data/BOUT.inp
  tests/integrated/test-snb/makefile
  tests/integrated/test-snb/runtest
  tests/integrated/test-snb/test_snb.cxx
Labels: feature

#1768 Try GitHub url for SUNDIALS if LLNL url fails
  .build_sundials_for_travis.sh
Labels: bugfix

#1769 Add processor indices to dump files
  src/mesh/impls/bout/boutmesh.cxx
Labels: small-change

#1764 More expressions "improvements"
  include/bout/sys/expressionparser.hxx
  include/field_factory.hxx
  manual/sphinx/user_docs/bout_options.rst
  manual/sphinx/user_docs/variable_init.rst
  src/field/field_factory.cxx
  src/field/fieldgenerators.hxx
  src/sys/expressionparser.cxx
  src/sys/options/options_ini.cxx
  tests/unit/field/test_field_factory.cxx
  tests/unit/sys/test_expressionparser.cxx
  tests/unit/sys/test_optionsreader.cxx
Labels: feature

#1767 Fix reading of zShift_ylow
  src/mesh/coordinates.cxx
  src/mesh/parallel/shiftedmetric.cxx
Labels: bugfix, small-change

#1766 Fixes for Python DataFile class
  tools/pylib/boututils/datafile.py
Labels: auxiliary-tools, bugfix, small-change

#1765 Fix y-boundary cells of phi in conducting-wall-mode example
  examples/conducting-wall-mode/README.md
  examples/conducting-wall-mode/cwm.cxx
  examples/conducting-wall-mode/data/BOUT.inp
Labels: bugfix, small-change
