Repository boutproject/BOUT-dev, pull requests merged in 2019-12, with the labels that each got.

#1859 Fix PETSc Laplace tests
  tests/integrated/test-petsc_laplace/data/BOUT.inp
  tests/integrated/test-petsc_laplace/test_petsc_laplace.cxx
  tests/integrated/test-petsc_laplace_MAST-grid/data/BOUT.inp
  tests/integrated/test-petsc_laplace_MAST-grid/test_petsc_laplace_MAST_grid.cxx
Labels: bugfix

#1851 Bugfix: $MPIRUN should include -np
  tests/integrated/test-coordinates-initialization/runtest
Labels: bugfix, easyfix

#1853 Loosen tolerance for other arches
  tests/unit/mesh/parallel/test_shiftedmetric.cxx
Labels: bugfix

#1860 Mesh requires Option to stay around.
  tools/pylib/_boutcore_build/boutcore.pyx.in
Labels: PythonInterface, bugfix

#1855 Address needs to be aligned
  tools/pylib/_boutcore_build/helper.h.in
Labels: bugfix

#1856 Try to prevent race condition while building.
  make.config.in
Labels: bugfix

#1862 Remove 3-element list indexers for collect()
  tools/pylib/boutdata/collect.py
Labels: auxiliary-tools, breaking change, small-change

#1867 Add BOUT_REVISION (git hash of compiled version) to dump files
  src/bout++.cxx
  src/fileio/datafile.cxx
  tests/unit/src/test_bout++.cxx
Labels: bugfix, small-change
