Repository boutproject/BOUT-dev, pull requests merged in 2020-08, with the labels that each got.

#2076 Correct Grad2_par2 implementation in InvertParCR (master)
  include/bout/surfaceiter.hxx
  src/invert/parderiv/impls/cyclic/cyclic.cxx
  src/invert/parderiv/impls/cyclic/cyclic.hxx
  src/mesh/surfaceiter.cxx
  tests/integrated/test-invpar/data/BOUT.inp
  tests/integrated/test-invpar/runtest
  tests/integrated/test-invpar/test_invpar.cxx
  tests/integrated/test-invpar/test_io.grd.nc
Labels: bugfix

#2077 Correct Grad2_par2 implementation in InvertParCR (v4.4.0)
  .github/workflows/clang-format-command.yml
  .github/workflows/slash-command-dispatch.yml
  include/bout/surfaceiter.hxx
  make.config.in
  manual/sphinx/user_docs/staggered_grids.rst
  src/invert/parderiv/impls/cyclic/cyclic.cxx
  src/invert/parderiv/impls/cyclic/cyclic.hxx
  src/mesh/difops.cxx
  src/mesh/surfaceiter.cxx
  tests/integrated/test-invpar/data/BOUT.inp
  tests/integrated/test-invpar/runtest
  tests/integrated/test-invpar/test_invpar.cxx
  tests/integrated/test-invpar/test_io.grd.nc
  tools/pylib/_boutcore_build/boutcore.pyx.in
  tools/pylib/_boutcore_build/helper.h.in
Labels: bugfix

#2074 CI: Turn off patch coverage check
  .codecov.yml
Labels: small-change

#2071 Correct Grad2_par2 implementation in InvertParCR
  include/bout/surfaceiter.hxx
  src/invert/parderiv/impls/cyclic/cyclic.cxx
  src/invert/parderiv/impls/cyclic/cyclic.hxx
  src/mesh/surfaceiter.cxx
  tests/integrated/test-invpar/CMakeLists.txt
  tests/integrated/test-invpar/data/BOUT.inp
  tests/integrated/test-invpar/runtest
  tests/integrated/test-invpar/test_invpar.cxx
  tests/integrated/test-invpar/test_io.grd.nc
Labels: backport candidiate, bugfix

#2070 Minor optimization of cyclic InvertPar implementation
  src/invert/parderiv/impls/cyclic/cyclic.cxx
Labels: performance, small-change
