Repository boutproject/BOUT-dev, pull requests merged in 2020-02, with the labels that each got.

#1841 Macro for creating enum classes
  include/bout/bout_enum_class.hxx
  manual/sphinx/user_docs/bout_options.rst
Labels: backport candidiate, feature, proposal

#1895 Macro for creating enum classes (v4.4)
  include/bout/bout_enum_class.hxx
  manual/sphinx/user_docs/bout_options.rst
Labels: feature

#1908 Laplace performance test
  examples/performance/laplace/.gitignore
  examples/performance/laplace/README.md
  examples/performance/laplace/data/BOUT.inp
  examples/performance/laplace/laplace.cxx
  examples/performance/laplace/makefile
  examples/performance/laplace/runtest
Labels: backport candidiate

#1877 Implement toFieldAligned and fromFieldAligned for Vector3D
  include/vector2d.hxx
  include/vector3d.hxx
  src/field/vector2d.cxx
  src/field/vector3d.cxx
Labels: backport candidiate, feature, small-change

#1878 Implement toFieldAligned and fromFieldAligned for Vector3D (v4.4)
  include/vector2d.hxx
  include/vector3d.hxx
  src/field/vector2d.cxx
  src/field/vector3d.cxx
Labels: feature, small-change
