Repository boutproject/BOUT-dev, pull requests merged in 2020-05, with the labels that each got.

#2028 Update the staggered grids section of the manual
  manual/sphinx/user_docs/staggered_grids.rst
Labels: documentation

#2029 Update the staggered grids section of the manual (to master)
  manual/sphinx/user_docs/staggered_grids.rst
Labels: documentation

#2031 Fix and unit tests for BOUT_ENUM_CLASS
  include/bout/bout_enum_class.hxx
  tests/unit/CMakeLists.txt
  tests/unit/include/bout/test_bout_enum_class.cxx
Labels: bugfix, small-change, tests

#1795 Allow PETSc options to be passed from BOUT.inp
  include/bout/invertable_operator.hxx
  include/bout/petsclib.hxx
  manual/sphinx/index.rst
  manual/sphinx/user_docs/petsc.rst
  src/invert/laplace/impls/petsc/petsc_laplace.cxx
  src/invert/laplace/impls/petsc3damg/petsc3damg.cxx
  src/invert/laplacexy/laplacexy.cxx
  src/invert/laplacexz/impls/petsc/laplacexz-petsc.cxx
  src/sys/petsclib.cxx
Labels: backport candidiate, feature

#2038 Add location checks to Div_par_K_Grad_par
  src/mesh/difops.cxx
Labels: backport candidiate, bugfix

#2039 Add location checks to Div_par_K_Grad_par
  src/mesh/difops.cxx
Labels: bugfix

#2035 Minor optimizations for ZHermiteSpline
  include/interpolation_z.hxx
  src/mesh/interpolation/hermite_spline_z.cxx
  src/mesh/parallel/shiftedmetricinterp.cxx
Labels: performance

#2042 Add PhysicsModel::mesh/dump members
  CHANGELOG.md
  examples/6field-simple/elm_6f.cxx
  examples/IMEX/advection-reaction/split_operator.cxx
  examples/advdiff2/init.cxx
  examples/advdiff2/run.cxx
  examples/bout_runners_example/diffusion_3D.cxx
  examples/conduction-snb/conduction-snb.cxx
  examples/constraints/laplace-dae/laplace_dae.cxx
  examples/finite-volume/test/finite_volume.cxx
  examples/laplace-petsc3d/test-laplace3d.cxx
  examples/laplacexy/laplace_perp/test.cxx
  examples/laplacexy/simple/test-laplacexy.cxx
  examples/performance/bracket/bracket.cxx
  examples/performance/communications/communications.cxx
  examples/performance/ddx/ddx.cxx
  examples/performance/ddy/ddy.cxx
  examples/performance/ddz/ddz.cxx
  examples/performance/iterator-offsets/iterator-offsets.cxx
  examples/performance/iterator/iterator.cxx
  examples/performance/laplace/laplace.cxx
  examples/performance/tuning_regionblocksize/tuning_regionblocksize.cxx
  examples/preconditioning/wave/test_precon.cxx
  examples/staggered_grid/test_staggered.cxx
  include/bout.hxx
  include/bout/physicsmodel.hxx
  src/physics/physicsmodel.cxx
  tests/MMS/diffusion/diffusion.cxx
  tests/MMS/spatial/fci/fci_mms.cxx
  tests/integrated/test-attribs/test-attribs.cxx
  tests/integrated/test-communications/test-communications.cxx
  tests/integrated/test-coordinates-initialization/test-coordinates-initialization.cxx
  tests/integrated/test-cyclic/test_cyclic.cxx
  tests/integrated/test-drift-instability/2fluid.cxx
  tests/integrated/test-fieldfactory/test_fieldfactory.cxx
  tests/integrated/test-griddata-yboundary-guards/test_griddata.cxx
  tests/integrated/test-griddata/test_griddata.cxx
  tests/integrated/test-gyro/test_gyro.cxx
  tests/integrated/test-initial/test_initial.cxx
  tests/integrated/test-interpolate-z/test_interpolate.cxx
  tests/integrated/test-interpolate/test_interpolate.cxx
  tests/integrated/test-invpar/test_invpar.cxx
  tests/integrated/test-io/test_io.cxx
  tests/integrated/test-laplace-petsc3d/test-laplace3d.cxx
  tests/integrated/test-laplace/test_laplace.cxx
  tests/integrated/test-laplacexy-fv/test-laplacexy.cxx
  tests/integrated/test-laplacexy-short/test-laplacexy.cxx
  tests/integrated/test-multigrid_laplace/test_multigrid_laplace.cxx
  tests/integrated/test-naulin-laplace/test_naulin_laplace.cxx
  tests/integrated/test-options-netcdf/test-options-netcdf.cxx
  tests/integrated/test-petsc_laplace/test_petsc_laplace.cxx
  tests/integrated/test-petsc_laplace_MAST-grid/test_petsc_laplace_MAST_grid.cxx
  tests/integrated/test-region-iterator/test_region_iterator.cxx
  tests/integrated/test-smooth/test_smooth.cxx
  tests/integrated/test-snb/test_snb.cxx
  tests/integrated/test-stopCheck-file/test_stopCheck.cxx
  tests/integrated/test-stopCheck/test_stopCheck.cxx
  tests/integrated/test-twistshift-staggered/test-twistshift.cxx
  tests/integrated/test-twistshift/test-twistshift.cxx
  tests/integrated/test-yupdown-weights/test_yupdown_weights.cxx
  tests/integrated/test-yupdown/test_yupdown.cxx
Labels: breaking change
