Repository boutproject/BOUT-dev, pull requests merged in 2020-09, with the labels that each got.

#2090 Fix current Travis failures in next
  .travis.yml
  .travis_fedora.sh
  tests/integrated/test-laplace-petsc3d/data_circular_core-sol/BOUT.inp
  tests/integrated/test-laplace-petsc3d/data_circular_core/BOUT.inp
  tests/integrated/test-laplace-petsc3d/data_slab_core/BOUT.inp
  tests/integrated/test-laplace-petsc3d/data_slab_sol/BOUT.inp
Labels: bugfix, small-change

#2087 Staggered grids in InvertPar
  CHANGELOG.md
  bin/bout-v5-factory-upgrader.py
  include/bout/snb.hxx
  include/invert_parderiv.hxx
  src/invert/parderiv/impls/cyclic/cyclic.cxx
  src/invert/parderiv/impls/cyclic/cyclic.hxx
  tests/integrated/test-invpar/data/BOUT.inp
  tests/integrated/test-invpar/runtest
  tests/integrated/test-invpar/test_invpar.cxx
Labels: backport candidiate, breaking change, feature

#2088 Staggered grids in InvertPar (v4.4.0)
  CMakeLists.txt
  include/invert_parderiv.hxx
  src/invert/parderiv/impls/cyclic/cyclic.cxx
  src/invert/parderiv/impls/cyclic/cyclic.hxx
  src/invert/parderiv/invert_parderiv.cxx
  src/invert/parderiv/parderiv_factory.cxx
  src/invert/parderiv/parderiv_factory.hxx
  tests/integrated/test-invpar/data/BOUT.inp
  tests/integrated/test-invpar/runtest
  tests/integrated/test-invpar/test_invpar.cxx
Labels: feature

#2103 CI: Turn off patch coverage check (master)
  .codecov.yml
Labels: small-change

#2093 Handle FieldPerps in Datafile::varAdded() and Datafile::varPtr()
  src/fileio/datafile.cxx
  tests/integrated/test-io/runtest
  tests/integrated/test-io/test_io.cxx
  tests/integrated/test-io_hdf5/runtest
  tests/integrated/test-io_hdf5/test_io_hdf5.cxx
Labels: bugfix

#2102 Fix some HDF5 related issues and add Mesh::getLocal{X,Y,Z}Index
  .travis.yml
  .travis_fedora.sh
  examples/laplace-petsc3d/create-initial-profiles.cxx
  include/bout/mesh.hxx
  src/fileio/dataformat.cxx
  src/fileio/impls/hdf5/h5_format.cxx
  src/mesh/impls/bout/boutmesh.cxx
  src/mesh/impls/bout/boutmesh.hxx
  tests/integrated/test-communications/CMakeLists.txt
  tests/integrated/test-communications/runtest
  tests/integrated/test-cyclic/CMakeLists.txt
  tests/integrated/test-drift-instability-staggered/CMakeLists.txt
  tests/integrated/test-drift-instability/CMakeLists.txt
  tests/integrated/test-drift-instability/runtest
  tests/integrated/test-fieldgroupComm/CMakeLists.txt
  tests/integrated/test-fieldgroupComm/runtest
  tests/integrated/test-griddata-yboundary-guards/CMakeLists.txt
  tests/integrated/test-gyro/CMakeLists.txt
  tests/integrated/test-interchange-instability/CMakeLists.txt
  tests/integrated/test-invpar/data/BOUT.inp
  tests/integrated/test-io_hdf5/runtest
  tests/integrated/test-io_hdf5/test_io_hdf5.cxx
  tests/integrated/test-laplace-petsc3d/CMakeLists.txt
  tests/integrated/test-laplace/CMakeLists.txt
  tests/integrated/test-restart-io/runtest
  tests/integrated/test-restart-io_hdf5/runtest
  tests/integrated/test-restarting/runtest
  tests/integrated/test-smooth/CMakeLists.txt
  tests/unit/test_extras.hxx
Labels: backport candidiate, bugfix

#2109 Update documentation on processor splitting and advanced installation
  manual/sphinx/user_docs/advanced_install.rst
  manual/sphinx/user_docs/bout_options.rst
  manual/sphinx/user_docs/installing.rst
Labels: documentation

#2095 Handle FieldPerps in Datafile::varAdded() and Datafile::varPtr() (next)
  src/fileio/datafile.cxx
  tests/integrated/test-io/data/benchmark.out.0.nc
  tests/integrated/test-io/runtest
  tests/integrated/test-io/test_io.cxx
  tests/integrated/test-io_hdf5/data/benchmark.out.0.hdf5
  tests/integrated/test-io_hdf5/runtest
  tests/integrated/test-io_hdf5/test_io_hdf5.cxx
Labels: bugfix
