Repository boutproject/BOUT-dev, pull requests merged in 2020-01, with the labels that each got.

#1876 If variable is added to Datafile twice, do not write twice
  src/fileio/datafile.cxx
  tests/integrated/test-io/runtest
  tests/integrated/test-io/test_io.cxx
Labels: bugfix

#1875 Fix loss of restart files caused by crash during initialisation
  src/physics/physicsmodel.cxx
Labels: bugfix

#1881 CMake: fix FindSlepc for non-make generators
  cmake/FindSLEPc.cmake
Labels: small-change

#1705 FieldGenerate refactor
  CMakeLists.txt
  include/boundary_region.hxx
  include/bout/sys/expressionparser.hxx
  include/bout/sys/generator_context.hxx
  include/field_factory.hxx
  manual/sphinx/user_docs/bout_options.rst
  manual/sphinx/user_docs/variable_init.rst
  src/field/field_factory.cxx
  src/field/fieldgenerators.cxx
  src/field/fieldgenerators.hxx
  src/mesh/boundary_standard.cxx
  src/mesh/data/gridfromoptions.cxx
  src/mesh/parallel_boundary_op.cxx
  src/sys/expressionparser.cxx
  src/sys/generator_context.cxx
  src/sys/makefile
  src/sys/options.cxx
  src/sys/options/options_ini.cxx
  tests/MMS/wave-1d/wave.cxx
  tests/integrated/test-interpolate/test_interpolate.cxx
  tests/unit/field/test_field_factory.cxx
  tests/unit/sys/test_expressionparser.cxx
  tests/unit/sys/test_optionsreader.cxx
Labels: feature

#1888 fix citation
  CITATION.bib
  CITATION.cff
Labels: small-change

#1887 Remove unused parameters to silence warnings in MsgStack
  include/msg_stack.hxx
Labels: small-change

#1882 Generate report for Timers
  include/bout/sys/timer.hxx
  src/bout++.cxx
  src/sys/timer.cxx
  tests/unit/sys/test_timer.cxx
Labels: backport candidiate

#1891 Rename death tests according to gtest recommendations
  tests/unit/src/test_bout++.cxx
Labels: backport candidiate, small-change
