Repository boutproject/BOUT-dev, pull requests merged in 2020-03, with the labels that each got.

#1922 Workaround for Petsc init/finialise not being idempotent
  tests/unit/bout_test_main.cxx
Labels: bugfix

#1927 Fix segfaults from PvodeSolver (master)
  src/solver/impls/cvode/cvode.cxx
  src/solver/impls/cvode/cvode.hxx
  src/solver/impls/pvode/pvode.cxx
  src/solver/impls/pvode/pvode.hxx
Labels: bugfix

#1926 Fix segfaults from PvodeSolver
  src/solver/impls/cvode/cvode.cxx
  src/solver/impls/cvode/cvode.hxx
  src/solver/impls/pvode/pvode.cxx
  src/solver/impls/pvode/pvode.hxx
Labels: backport candidiate, bugfix

#1896 XZInterpolation rename, and passing Options to XZInterpolation objects
  CMakeLists.txt
  bin/bout-v5-input-file-upgrader.py
  bin/bout-v5-xzinterpolation-upgrader.py
  bin/bout_4to5_header_file_list
  examples/6field-simple/data/BOUT.inp
  examples/conducting-wall-mode/cwm.cxx
  examples/constraints/alfven-wave/alfven.cxx
  examples/constraints/alfven-wave/cbm18/BOUT.inp
  examples/constraints/alfven-wave/data/BOUT.inp
  examples/dalf3/dalf3.cxx
  examples/elm-pb/data/BOUT.inp
  examples/em-drift/2fluid.cxx
  examples/fci-wave-logn/boundary/BOUT.inp
  examples/fci-wave-logn/div-integrate/BOUT.inp
  examples/fci-wave-logn/expanded/BOUT.inp
  examples/fci-wave/div-integrate/BOUT.inp
  examples/fci-wave/div/BOUT.inp
  examples/fci-wave/logn/BOUT.inp
  examples/gyro-gem/data/BOUT.inp
  examples/jorek-compare/data/BOUT.inp
  examples/jorek-compare/jorek_compare.cxx
  examples/lapd-drift/lapd_drift.cxx
  examples/laplacexy/alfven-wave/cbm18/BOUT.inp
  examples/laplacexy/alfven-wave/data/BOUT.inp
  examples/reconnect-2field/data/BOUT.inp
  examples/shear-alfven-wave/2fluid.cxx
  examples/tokamak-2fluid/2fluid.cxx
  examples/tokamak-2fluid/d3d-119919/BOUT.inp
  examples/tokamak-2fluid/d3d-129131/BOUT.inp
  include/bout/generic_factory.hxx
  include/bout/paralleltransform.hxx
  include/interpolation.hxx
  include/interpolation_xz.hxx
  src/bout++.cxx
  src/mesh/coordinates.cxx
  src/mesh/interpolation/bilinear_xz.cxx
  src/mesh/interpolation/hermite_spline_xz.cxx
  src/mesh/interpolation/lagrange_4pt_xz.cxx
  src/mesh/interpolation/makefile
  src/mesh/interpolation/monotonic_hermite_spline_xz.cxx
  src/mesh/interpolation_xz.cxx
  src/mesh/makefile
  src/mesh/parallel/fci.cxx
  src/mesh/parallel/fci.hxx
  src/mesh/parallel/shiftedmetric.cxx
  tests/MMS/spatial/fci/data/BOUT.inp
  tests/MMS/spatial/fci/runtest
  tests/MMS/tokamak/data/BOUT.inp
  tests/integrated/test-interpolate/data/BOUT.inp
  tests/integrated/test-interpolate/runtest
  tests/integrated/test-interpolate/test_interpolate.cxx
  tests/integrated/test-twistshift-staggered/data/BOUT.inp
  tests/integrated/test-twistshift/data/BOUT.inp
  tests/integrated/test-yupdown/data/BOUT.inp
  tools/pylib/boutdata/data.py
Labels: breaking change

#1925 Fixes for staggering in lapd-drift example
  examples/lapd-drift/data/BOUT.inp
  examples/lapd-drift/lapd_drift.cxx
Labels: backport candidiate, bugfix

#1928 Fixes for staggering in lapd-drift example (master)
  examples/lapd-drift/data/BOUT.inp
  examples/lapd-drift/lapd_drift.cxx
Labels: bugfix

#1942 Minor Travis fixes and job names
  .travis.yml
Labels: backport candidiate

#1869 Basic lock for mpark.variant
  make.config.in
Labels: bugfix

#1947 Ignore latexmk files
  .gitignore
Labels: auxiliary-tools, small-change

#1890 Add Mesh::getRegion<T> for use in generic code
  include/bout/mesh.hxx
  include/bout/region.hxx
  tests/unit/mesh/test_mesh.cxx
Labels: backport candidiate, small-change

#1949 Remove FieldData::setBoundary
  include/field_data.hxx
  src/field/field_data.cxx
Labels: bugfix

#1950 Fix lapd_drift input files
  examples/lapd-drift/data/BOUT.inp
  examples/lapd-drift/lapd/BOUT.inp
  examples/lapd-drift/pisces/BOUT.inp
Labels: bugfix

#1953 make README.md readabile
  tools/README.md
Labels: small-change

#1944 Add ZInterpolation, ZHermiteSpline
  CMakeLists.txt
  bin/bout_4to5_header_file_list
  include/interpolation.hxx
  include/interpolation_z.hxx
  include/mask.hxx
  src/bout++.cxx
  src/mesh/interpolation/hermite_spline_z.cxx
  src/mesh/interpolation/makefile
  tests/integrated/CMakeLists.txt
  tests/integrated/test-interpolate-z/CMakeLists.txt
  tests/integrated/test-interpolate-z/data/BOUT.inp
  tests/integrated/test-interpolate-z/makefile
  tests/integrated/test-interpolate-z/runtest
  tests/integrated/test-interpolate-z/test_interpolate.cxx
Labels: feature

#1939 Add full perpendicular Laplacian, inverse of LaplaceXY
  include/bout/coordinates.hxx
  include/difops.hxx
  src/mesh/coordinates.cxx
  src/mesh/difops.cxx
  tests/integrated/CMakeLists.txt
  tests/integrated/test-laplacexy-fv/CMakeLists.txt
  tests/integrated/test-laplacexy-fv/data/BOUT.inp
  tests/integrated/test-laplacexy-fv/makefile
  tests/integrated/test-laplacexy-fv/plotcheck.py
  tests/integrated/test-laplacexy-fv/runtest
  tests/integrated/test-laplacexy-fv/test-laplacexy.cxx
  tests/unit/include/bout/test_stencil.cxx
Labels: feature

#1920 Generate version header
  CHANGELOG.md
  CMakeLists.txt
  bin/bout-config.in
  bin/bout-v5-macro-upgrader.py
  configure
  configure.ac
  include/bout.hxx
  include/bout/revision.hxx.in
  include/bout/version.hxx.in
  make.config.in
  src/bout++.cxx
  src/makefile
  src/physics/physicsmodel.cxx
  tests/integrated/test-griddata/test_griddata.cxx
  tests/unit/src/test_bout++.cxx
Labels: breaking change

#1885 Set corner cells consistently
  examples/performance/communications/communications.cxx
  examples/performance/communications/data/BOUT.inp
  examples/performance/communications/data/BOUT.inp.smallblocks
  examples/performance/communications/data/BOUT.inp.standard
  examples/performance/communications/makefile
  include/bout/mesh.hxx
  manual/sphinx/developer_docs/mesh.rst
  manual/sphinx/user_docs/boundary_options.rst
  src/mesh/coordinates.cxx
  src/mesh/impls/bout/boutmesh.cxx
  src/mesh/impls/bout/boutmesh.hxx
  src/mesh/mesh.cxx
  tests/integrated/test-communications/corner_communication_diagram.ods
  tests/integrated/test-communications/data/BOUT.inp
  tests/integrated/test-communications/data_limiter/BOUT.inp
  tests/integrated/test-communications/makefile
  tests/integrated/test-communications/runtest
  tests/integrated/test-communications/test-communications.cxx
  tests/unit/test_extras.hxx
Labels: feature, proposal

#1957 Exclude corner cells in LaplaceXY
  src/invert/laplacexy/laplacexy.cxx
  src/mesh/interpolation/hermite_spline_xz.cxx
  src/mesh/interpolation/hermite_spline_z.cxx
  src/mesh/interpolation/monotonic_hermite_spline_xz.cxx
  tests/integrated/test-yupdown-weights/runtest
Labels: bugfix

#1943 Fix some missed fmt format strings
  include/bout/bout_enum_class.hxx
  src/field/fieldgenerators.hxx
  src/sys/options/options_ini.cxx
  tests/MMS/wave-1d/wave.cxx
  tests/unit/fake_parallel_mesh.hxx
Labels: bugfix, small-change

#1955 Fix possible data race in MsgStack::push()
  src/sys/msg_stack.cxx
Labels: bugfix, small-change

#1912 CMake: find package fixes
  bout++Config.cmake.in
  cmake/FindNetCDF.cmake
  cmake/FindPETSc.cmake
Labels: build-system

#1961 Pass method and region arguments to D2DXDY in Laplace(Field2D)
  src/mesh/coordinates.cxx
Labels: bugfix, small-change

#1900 CMake: enable using external mpark.variant
  CMakeLists.txt
  bout++Config.cmake.in
  cmake/FindNetCDF.cmake
  manual/sphinx/user_docs/installing.rst
  tests/unit/CMakeLists.txt
Labels: build-system

#1956 Fix deprecated initialisation and boundary options
  examples/2Dturbulence_multigrid/data/BOUT.inp
  examples/IMEX/advection-reaction/data/BOUT.inp
  examples/advdiff2/data/BOUT.inp
  examples/constraints/laplace-dae/data/BOUT.inp
  examples/dalf3/data/BOUT.inp
  examples/elm-pb/Python/data/BOUT.inp
  examples/elm-pb/Python/data0/BOUT.inp
  examples/elm-pb/eigen/BOUT.inp
  examples/elm-pb/test/BOUT.inp
  examples/gas-compress/advect1d/BOUT.inp
  examples/gas-compress/sod-shock/BOUT.inp
  examples/lapd-drift/BOUT.inp
  examples/lapd-drift/BOUT.inp.nn
  examples/lapd-drift/BOUT.inp.nn_zem
  examples/lapd-drift/data/BOUT.inp
  examples/lapd-drift/lapd/BOUT.inp
  examples/lapd-drift/pisces/BOUT.inp
  examples/orszag-tang/data/BOUT.inp_1
  examples/shear-alfven-wave/data/BOUT.inp
  examples/tokamak-2fluid/data/BOUT.inp
  examples/tokamak-2fluid/data/BOUT.inp_nl
  examples/tokamak-2fluid/data/BOUT.inp_simple
  examples/uedge-benchmark/data/BOUT.inp
  tests/MMS/diffusion/data/BOUT.inp
  tests/MMS/diffusion2/X/BOUT.inp
  tests/MMS/diffusion2/XYZ/BOUT.inp
  tests/MMS/diffusion2/Y/BOUT.inp
  tests/MMS/diffusion2/Z/BOUT.inp
  tests/MMS/spatial/diffusion/X/BOUT.inp
  tests/MMS/wave-1d/data/BOUT.inp
  tests/integrated/test-invpar/data/BOUT.inp
  tests/integrated/test-invpar/runtest
  tests/integrated/test-simple-diffusion/data/BOUT.inp
  tests/integrated/test-simple-diffusion/data/advect.grd.cdl
  tests/integrated/test-simple-diffusion/data/advect.grd.pdb
  tests/integrated/test-simple-diffusion/generate.pro
  tests/integrated/test-simple-diffusion/makefile
  tests/integrated/test-simple-diffusion/runcase.sh
  tests/integrated/test-simple-diffusion/runidl.pro
  tests/integrated/test-simple-diffusion/simple_diff.cxx
Labels: bugfix

#1963 Fix typo in example/performance/communications
  examples/performance/communications/communications.cxx
Labels: small-change

#1973 Remove reference to deleted test in documentation
  manual/sphinx/user_docs/running_bout.rst
Labels: small-change

#1971 Fix documented requirements
  README.md
  manual/sphinx/user_docs/installing.rst
Labels: documentation, small-change

#1975 Read staggered J and Bxy from grid if present (master)
  src/mesh/coordinates.cxx
Labels: bugfix

#1985 fix test-laplace-petsc3d
  tests/integrated/test-laplace-petsc3d/runtest
Labels: bugfix, small-change

#1983 Use custom main instead of PhysicsModel in test-communications
  tests/integrated/CMakeLists.txt
  tests/integrated/test-communications/CMakeLists.txt
  tests/integrated/test-communications/runtest
  tests/integrated/test-communications/test-communications.cxx
Labels: bugfix, small-change

#1994 Travis: Update pinned pip packages
  .pip_install_for_travis.sh
  .travis.yml
Labels: small-change

#1972 Remove -Og from debug flags
  configure
  configure.ac
Labels: small-change

#2001 Include smaller "fmt/core.h"
  include/bout/sys/expressionparser.hxx
  include/boutexception.hxx
  include/datafile.hxx
  include/msg_stack.hxx
  include/optionsreader.hxx
  include/output.hxx
  src/bout++.cxx
  src/sys/boutexception.cxx
  src/sys/timer.cxx
Labels: small-change
