Repository boutproject/BOUT-dev, pull requests merged in 2020-12, with the labels that each got.

#2157 Fix shiftOutput
  include/dataformat.hxx
  src/fileio/datafile.cxx
  src/fileio/dataformat.cxx
Labels: backport candidiate, bugfix

#2156 Migrate to GitHub Actions
  .github/workflows/clang-tidy-review.yml
  .github/workflows/tests.yml
  .travis.yml
Labels: tests

#2163 Stringify BOUT_REVISION when passed as a define on the command line
  include/bout/revision.hxx.in
Labels: bugfix

#2158 Fix shiftOutput (master)
  include/dataformat.hxx
  src/fileio/datafile.cxx
  src/fileio/dataformat.cxx
Labels: bugfix

#2153 I/O for std::vector<int> and std::string
  include/datafile.hxx
  include/dataformat.hxx
  src/fileio/datafile.cxx
  src/fileio/impls/hdf5/h5_format.cxx
  src/fileio/impls/hdf5/h5_format.hxx
  src/fileio/impls/netcdf/nc_format.cxx
  src/fileio/impls/netcdf/nc_format.hxx
  src/fileio/impls/netcdf4/ncxx4.cxx
  src/fileio/impls/netcdf4/ncxx4.hxx
  tests/integrated/test-io/data/benchmark.out.0.nc
  tests/integrated/test-io/runtest
  tests/integrated/test-io/test_io.cxx
  tests/integrated/test-io_hdf5/data/benchmark.out.0.hdf5
  tests/integrated/test-io_hdf5/runtest
  tests/integrated/test-io_hdf5/test_io_hdf5.cxx
Labels: backport candidiate, feature

#2155 I/O for std::vector<int> and std::string (4.4)
  include/datafile.hxx
  include/dataformat.hxx
  src/fileio/datafile.cxx
  src/fileio/impls/hdf5/h5_format.cxx
  src/fileio/impls/hdf5/h5_format.hxx
  src/fileio/impls/netcdf/nc_format.cxx
  src/fileio/impls/netcdf/nc_format.hxx
  src/fileio/impls/netcdf4/ncxx4.cxx
  src/fileio/impls/netcdf4/ncxx4.hxx
  tests/integrated/test-io/data/benchmark.out.0.nc
  tests/integrated/test-io/runtest
  tests/integrated/test-io/test_io.cxx
  tests/integrated/test-io_hdf5/data/benchmark.out.0.hdf5
  tests/integrated/test-io_hdf5/runtest
  tests/integrated/test-io_hdf5/test_io_hdf5.cxx
Labels: feature

#2152 Add ability to use FieldPerp in Options
  include/bout/sys/type_name.hxx
  include/fieldperp.hxx
  include/options.hxx
  src/field/field.cxx
  src/field/field3d.cxx
  src/field/fieldperp.cxx
  src/fileio/dataformat.cxx
  src/sys/options.cxx
  src/sys/options/options_netcdf.cxx
  src/sys/type_name.cxx
  tests/integrated/test-options-netcdf/runtest
  tests/integrated/test-options-netcdf/test-options-netcdf.cxx
  tests/unit/field/test_field3d.cxx
  tests/unit/field/test_fieldperp.cxx
  tests/unit/sys/test_options.cxx
  tests/unit/sys/test_options_netcdf.cxx
  tests/unit/test_extras.hxx
Labels: backport candidiate

#2154 Fix test-restart-io and FieldPerp writes
  CHANGELOG.md
  include/bout/mesh.hxx
  src/fileio/dataformat.cxx
  tests/integrated/test-io/data/benchmark.out.0.nc
  tests/integrated/test-io/test_io.grd.nc
  tests/integrated/test-restart-io/runtest
Labels: bugfix, small-change, tests

#2172 Docs: note more recent version of PETSc might work, but not guaranteed
  manual/sphinx/user_docs/advanced_install.rst
Labels: documentation, small-change

#2171 Update docs on supported PETSc versions
  manual/sphinx/user_docs/advanced_install.rst
Labels: documentation, small-change

#2175 Add requirements to boutcore/print test
  tests/integrated/test-boutcore/print/runtest
Labels: bugfix

#2010 Add `boutconfig` Python module with build configuration information
  CMakeLists.txt
  configure
  configure.ac
  make.config.in
  tools/pylib/boutconfig/__init__.py.cin
  tools/pylib/boutconfig/__init__.py.in
Labels: auxiliary-tools, feature

#2148 Check DataFile grid sizes match those in existing mesh (v4.4)
  src/fileio/datafile.cxx
  tests/integrated/test-io/data/benchmark.out.0.nc
  tests/integrated/test-io_hdf5/data/benchmark.out.0.hdf5
Labels: bugfix, small-change

#2176 CMake: Set PYTHONPATH for tests
  CMakeLists.txt
Labels: build-system

#2086 Allow descriptions of output variables; save some diagnostics for solvers (v4.4)
  include/bout/physicsmodel.hxx
  include/bout/solver.hxx
  include/boutmain.hxx
  include/datafile.hxx
  manual/sphinx/user_docs/physics_models.rst
  src/fileio/datafile.cxx
  src/physics/physicsmodel.cxx
  src/solver/impls/arkode/arkode.cxx
  src/solver/impls/arkode/arkode.hxx
  src/solver/impls/cvode/cvode.cxx
  src/solver/impls/cvode/cvode.hxx
  src/solver/impls/slepc/slepc.hxx
  src/solver/solver.cxx
Labels: documentation, feature

#2144 Add back some missing Fields documentation (and clang-format)
  include/field.hxx
Labels: documentation, small-change

#2064 Allow descriptions of output variables; save some diagnostics for solvers
  include/bout/physicsmodel.hxx
  include/bout/solver.hxx
  include/boutmain.hxx
  include/datafile.hxx
  manual/sphinx/user_docs/physics_models.rst
  src/fileio/datafile.cxx
  src/physics/physicsmodel.cxx
  src/solver/impls/arkode/arkode.cxx
  src/solver/impls/arkode/arkode.hxx
  src/solver/impls/cvode/cvode.cxx
  src/solver/impls/cvode/cvode.hxx
  src/solver/impls/slepc/slepc.hxx
  src/solver/solver.cxx
Labels: backport candidiate, documentation, feature

#2030 Iterative parallel tridiagonal solver
  CMakeLists.txt
  include/invert_laplace.hxx
  src/invert/laplace/impls/iterative_parallel_tri/iterative_parallel_tri.cxx
  src/invert/laplace/impls/iterative_parallel_tri/iterative_parallel_tri.hxx
  src/invert/laplace/impls/iterative_parallel_tri/makefile
  src/invert/laplace/impls/makefile
  src/invert/laplace/invert_laplace.cxx
Labels: feature
