Repository boutproject/BOUT-dev, pull requests merged in 2020-06, with the labels that each got.

#2044 MMS test for ShiftedMetricInterp
  tests/MMS/shiftedmetricinterp/data/BOUT.inp
  tests/MMS/shiftedmetricinterp/runtest
  tools/pylib/boutdata/data.py
Labels: tests

#1846 Adding an adaptive, arbitrary order, Adams-Bashforth solver
  CMakeLists.txt
  src/solver/impls/adams_bashforth/adams_bashforth.cxx
  src/solver/impls/adams_bashforth/adams_bashforth.hxx
  src/solver/impls/adams_bashforth/makefile
  src/solver/impls/makefile
  src/solver/solver.cxx
Labels: backport candidiate, proposal

#2049 Support multiple parallel slices in ShiftedMetricInterp
  CMakeLists.txt
  include/bout/paralleltransform.hxx
  include/interpolation_z.hxx
  src/mesh/interpolation/hermite_spline_z.cxx
  src/mesh/interpolation/interpolation_z.cxx
  src/mesh/interpolation/makefile
  src/mesh/parallel/shiftedmetricinterp.cxx
  src/mesh/parallel/shiftedmetricinterp.hxx
  tests/integrated/test-yupdown-weights/test_yupdown_weights.cxx
Labels: feature

#2053 Revert name of legacy netCDF macro
  configure
  configure.ac
Labels: bugfix, build-system

#2051 Tighten set tolerance for LaplacePetsc3dAmg test
  tests/unit/invert/laplace/test_laplace_petsc3damg.cxx
Labels: bugfix
