Repository boutproject/BOUT-dev, pull requests merged in 2020-11, with the labels that each got.

#2132 Allow setting FFTW_EXHAUSTIVE (v4.4)
  include/bout/bout_enum_class.hxx
  include/fft.hxx
  src/invert/fft_fftw.cxx
Labels: performance

#2094 Handle FieldPerps in Datafile::varAdded() and Datafile::varPtr() (v4.4.0)
  src/fileio/datafile.cxx
  tests/integrated/test-io/runtest
  tests/integrated/test-io/test_io.cxx
  tests/integrated/test-io_hdf5/runtest
  tests/integrated/test-io_hdf5/test_io_hdf5.cxx
Labels: bugfix

#2133 Call checkData() before returning result in Laplace inversions
  src/invert/laplace/impls/cyclic/cyclic_laplace.cxx
  src/invert/laplace/impls/multigrid/multigrid_laplace.cxx
  src/invert/laplace/impls/naulin/naulin_laplace.cxx
  src/invert/laplace/impls/pdd/pdd.cxx
  src/invert/laplace/impls/petsc/petsc_laplace.cxx
  src/invert/laplace/impls/petsc3damg/petsc3damg.cxx
  src/invert/laplace/impls/serial_band/serial_band.cxx
  src/invert/laplace/impls/serial_tri/serial_tri.cxx
  src/invert/laplace/impls/shoot/shoot_laplace.cxx
  src/invert/laplace/impls/spt/spt.cxx
Labels: backport candidiate

#2131 Allow setting FFTW_EXHAUSTIVE
  bin/bout-v5-input-file-upgrader.py
  include/fft.hxx
  manual/sphinx/user_docs/bout_options.rst
  src/invert/fft_fftw.cxx
Labels: backport candidiate, performance

#2136 Fix a couple of typos in zoidberg.field.GEQDSK
  tools/pylib/zoidberg/field.py
Labels: bugfix, small-change

#2137 Fix errors in tests/MMS/elm-pb
  tests/MMS/elm-pb/data/BOUT.inp
  tests/MMS/elm-pb/elm_pb.cxx
Labels: tests

#2135 Update InvertPar factory call in some examples
  examples/IMEX/diffusion-nl/diffusion-nl.cxx
  examples/elm-pb/elm_pb.cxx
  examples/preconditioning/wave/test_precon.cxx
  examples/reconnect-2field/2field.cxx
Labels: bugfix, small-change

#2130 Fix two issues with `build_defines` header
  cmake_build_defines.hxx.in
  make.config.in
Labels: bugfix, small-change

#2146 Relax security controls on Fedora test image
  .travis_fedora.sh
Labels: bugfix, small-change

#2147 Add a clamp function to FieldFactory
  manual/sphinx/user_docs/variable_init.rst
  src/field/field_factory.cxx
  src/field/fieldgenerators.hxx
  tests/unit/field/test_field_factory.cxx
Labels: small-change

#2145 Check DataFile grid sizes match those in existing mesh
  src/fileio/datafile.cxx
Labels: backport candidiate, bugfix, small-change
