Repository boutproject/BOUT-dev, pull requests merged in 2020-04, with the labels that each got.

#2011 Ensure quiet script isn't too verbose on error
  tests/unit/quiet.sh
Labels: small-change, tests

#2009 fix requires in options-netcdf test
  tests/integrated/test-options-netcdf/runtest
Labels: small-change, tests

#2005 Improve some error messages
  include/bout/fv_ops.hxx
  tests/integrated/test-twistshift-staggered/runtest
Labels: small-change

#2006 Ensure ffts are OpenMP thread safe
  src/invert/fft_fftw.cxx
Labels: small-change

#2007 Run wrapper improvements
  tools/pylib/boututils/run_wrapper.py
Labels: auxiliary-tools, small-change

#2015 Fix formatting of 'Obtaining BOUT++' section heading
  manual/sphinx/user_docs/installing.rst
Labels: documentation, small-change

#2017 Prevent deadlock in downloading mpark
  make.config.in
Labels: bugfix, build-system
