Repository boutproject/BOUT-dev, pull requests merged in 2020-10, with the labels that each got.

#2111 Suggestions for gnu build on Marconi
  manual/sphinx/user_docs/advanced_install.rst
Labels: documentation

#2114 Update breathe for readthedocs
  manual/sphinx/requirements.txt
Labels: bugfix, small-change

#2113 Fix Div_par when using more than one y guard cell
  src/mesh/coordinates.cxx
Labels: bugfix, small-change

#2043 Fixes for tokamak-2fluid example
  examples/tokamak-2fluid/2fluid.cxx
  examples/tokamak-2fluid/data/BOUT.inp
Labels: bugfix

#2116 Fix reading/writing std::string attributes when using HDF5
  src/fileio/impls/hdf5/h5_format.cxx
Labels: bugfix, small-change

#2115 Rename death tests according to gtest recommendations
  tests/unit/src/test_bout++.cxx
Labels: bugfix, small-change

#2122 Fix links to open-mpi.org and lam-mpi.org
  manual/sphinx/user_docs/installing.rst
Labels: documentation

#2125 Ignore more test data
  tests/integrated/.gitignore
Labels: small-change

#2127 Make example relocatable
  examples/2Dturbulence_multigrid/makefile
  examples/6field-simple/makefile
  examples/IMEX/advection-diffusion/makefile
  examples/IMEX/advection-reaction/makefile
  examples/IMEX/diffusion-nl/makefile
  examples/IMEX/drift-wave-constraint/makefile
  examples/IMEX/drift-wave/makefile
  examples/advdiff/makefile
  examples/advdiff2/makefile
  examples/backtrace/makefile
  examples/blob2d-laplacexz/makefile
  examples/blob2d/makefile
  examples/boundary-conditions/advection/makefile
  examples/bout_runners_example/makefile
  examples/conducting-wall-mode/makefile
  examples/conduction-snb/makefile
  examples/conduction/makefile
  examples/constraints/alfven-wave/makefile
  examples/constraints/laplace-dae/makefile
  examples/dalf3/makefile
  examples/eigen-box/makefile
  examples/elm-pb/makefile
  examples/em-drift/makefile
  examples/fci-wave-logn/makefile
  examples/fci-wave/makefile
  examples/finite-volume/diffusion/makefile
  examples/finite-volume/fluid/makefile
  examples/finite-volume/test/makefile
  examples/gas-compress/makefile
  examples/gravity_reduced/makefile
  examples/gyro-gem/makefile
  examples/hasegawa-wakatani/makefile
  examples/invertable_operator/makefile
  examples/jorek-compare/makefile
  examples/lapd-drift/makefile
  examples/laplacexy/alfven-wave/makefile
  examples/laplacexy/laplace_perp/makefile
  examples/laplacexy/simple/makefile
  examples/monitor-newapi/makefile
  examples/monitor/makefile
  examples/orszag-tang/makefile
  examples/performance/arithmetic/makefile
  examples/performance/arithmetic_3d2d/makefile
  examples/performance/bracket/makefile
  examples/performance/ddx/makefile
  examples/performance/ddy/makefile
  examples/performance/ddz/makefile
  examples/performance/iterator-offsets/makefile
  examples/performance/iterator/makefile
  examples/performance/laplace/makefile
  examples/performance/tuning_regionblocksize/makefile
  examples/preconditioning/wave/makefile
  examples/reconnect-2field/makefile
  examples/shear-alfven-wave/makefile
  examples/staggered_grid/makefile
  examples/subsampling/makefile
  examples/tokamak-2fluid/makefile
  examples/uedge-benchmark/makefile
  examples/wave-slab/makefile
Labels: small-change
