Repository boutproject/BOUT-dev, pull requests merged in 2021-06, with the labels that each got.

#2345 Fix for conditionally used boundary condition inputs in 'all'
  src/field/field_data.cxx
Labels: bugfix, small-change

#2329 Correct descriptive text in coordinates section of manual
  manual/sphinx/user_docs/coordinates.rst
Labels: documentation, small-change

#2347 CMake rename PACKAGE_TESTS to BOUT_TESTS
  CMakeLists.txt
Labels: build-system, small-change

#2346 Fixing up 6field-simple example in next
  examples/6field-simple/data/BOUT.inp
  examples/6field-simple/elm_6f.cxx
Labels: bugfix
