Repository boutproject/BOUT-dev, pull requests merged in 2021-05, with the labels that each got.

#2299 Update installation suggestions for Marconi/gnu
  manual/sphinx/user_docs/advanced_install.rst
  tools/pylib/zoidberg/field.py
Labels: documentation, small-change

#2294 Faster recompile
  CMakeLists.txt
  make.config.in
  src/bout++-time.cxx
  src/bout++-time.hxx
  src/bout++.cxx
  src/makefile.in
  tests/integrated/test-io/runtest
Labels: build-system

#2303 CVODE constraints and max_noinlinear_iterations options
  src/solver/impls/cvode/cvode.cxx
  src/solver/impls/cvode/cvode.hxx
Labels: backport candidiate, feature

#2304 CVODE constraints and max_noinlinear_iterations options (4.4)
  src/solver/impls/cvode/cvode.cxx
  src/solver/impls/cvode/cvode.hxx
Labels: feature

#2300 CMake: Build documentation
  .github/workflows/clang-tidy-review.yml
  .github/workflows/tests.yml
  CMakeLists.txt
  cmake/FindSphinx.cmake
  manual/CMakeLists.txt
Labels: build-system

#2308 Fix a couple of documentation issues
  manual/CMakeLists.txt
  manual/sphinx/conf.py
Labels: bugfix, documentation

#2310 Fix more documentation issues
  manual/CMakeLists.txt
  manual/sphinx/conf.py
Labels: bugfix, documentation

#2286 Add MMS tests to CMake build
  .github/workflows/clang-tidy-review.yml
  CMakeLists.txt
  cmake/BOUT++functions.cmake
  tests/MMS/CMakeLists.txt
  tests/MMS/advection/CMakeLists.txt
  tests/MMS/advection/arakawa/CMakeLists.txt
  tests/MMS/advection/arakawa/advection
  tests/MMS/advection/central/CMakeLists.txt
  tests/MMS/advection/central/advection
  tests/MMS/advection/runtest
  tests/MMS/advection/upwind/CMakeLists.txt
  tests/MMS/advection/upwind/advection
  tests/MMS/advection/weno3/CMakeLists.txt
  tests/MMS/advection/weno3/advection
  tests/MMS/diffusion/CMakeLists.txt
  tests/MMS/diffusion2/CMakeLists.txt
  tests/MMS/hw/CMakeLists.txt
  tests/MMS/laplace/CMakeLists.txt
  tests/MMS/laplace/laplace.cxx
  tests/MMS/spatial/advection/CMakeLists.txt
  tests/MMS/spatial/advection/advection.cxx
  tests/MMS/spatial/d2dx2/CMakeLists.txt
  tests/MMS/spatial/d2dx2/test_d2dx2.cxx
  tests/MMS/spatial/d2dz2/CMakeLists.txt
  tests/MMS/spatial/d2dz2/test_d2dz2.cxx
  tests/MMS/spatial/diffusion/CMakeLists.txt
  tests/MMS/spatial/fci/CMakeLists.txt
  tests/MMS/time-petsc/CMakeLists.txt
  tests/MMS/time/CMakeLists.txt
  tests/MMS/wave-1d-y/CMakeLists.txt
  tests/MMS/wave-1d/CMakeLists.txt
Labels: backport candidiate, build-system

#2306 Fix memory leak of Coordinates in unit tests
  include/field.hxx
  src/field/field.cxx
Labels: bugfix

#2315 Add missing snb.cxx to CMakeLists.txt
  CMakeLists.txt
Labels: bugfix, build-system, small-change

#2302 CMake: Add coverage/sanitizers
  CMakeLists.txt
  cmake/Sanitizers.cmake
Labels: build-system

#2284 Fix some Solvers not always using user preconditioner/Jacobian (v4.4)
  include/bout/solver.hxx
  src/solver/impls/arkode/arkode.cxx
  src/solver/impls/arkode/arkode.hxx
  src/solver/impls/cvode/cvode.cxx
  src/solver/impls/cvode/cvode.hxx
  src/solver/impls/ida/ida.cxx
  src/solver/impls/imex-bdf2/imex-bdf2.cxx
  src/solver/impls/petsc/petsc.cxx
  src/solver/impls/petsc/petsc.hxx
  src/solver/solver.cxx
  tests/unit/solver/test_fakesolver.hxx
  tests/unit/solver/test_solver.cxx
Labels: bugfix

#2283 Fix some Solvers not always using user preconditioner/Jacobian
  include/bout/solver.hxx
  src/solver/impls/arkode/arkode.cxx
  src/solver/impls/arkode/arkode.hxx
  src/solver/impls/cvode/cvode.cxx
  src/solver/impls/cvode/cvode.hxx
  src/solver/impls/ida/ida.cxx
  src/solver/impls/imex-bdf2/imex-bdf2.cxx
  src/solver/impls/petsc/petsc.cxx
  src/solver/impls/petsc/petsc.hxx
  src/solver/solver.cxx
  tests/unit/solver/test_fakesolver.hxx
  tests/unit/solver/test_solver.cxx
Labels: bugfix

#2317 Fix for FindPETSc not being reentrant if pkg-config used
  cmake/FindPETSc.cmake
Labels: bugfix, build-system

#2318 Fix for FindPETSc not being reentrant if pkg-config used (next)
  cmake/FindPETSc.cmake
Labels: bugfix, build-system

#2319 Fix ReadTheDocs (master)
  manual/sphinx/_static/css/custom.css
  manual/sphinx/conf.py
Labels: bugfix, documentation

#2325 Fix --enable-debug and --enable-checks
  configure
  configure.ac
Labels: build-system

#2331 CMake: Add option to download SUNDIALS at configure time
  CMakeLists.txt
  cmake/FindSUNDIALS.cmake
  manual/sphinx/user_docs/installing.rst
Labels: build-system

#2330 Parallel cyclic reduction
  CMakeLists.txt
  include/invert_laplace.hxx
  src/invert/laplace/impls/cyclic/cyclic_laplace.cxx
  src/invert/laplace/impls/cyclic/cyclic_laplace.hxx
  src/invert/laplace/impls/makefile
  src/invert/laplace/impls/pcr/makefile
  src/invert/laplace/impls/pcr/pcr.cxx
  src/invert/laplace/impls/pcr/pcr.hxx
  src/invert/laplace/invert_laplace.cxx
  tests/integrated/test-laplace/runtest
Labels: backport candidiate, feature

#2309 CMake: Add separate configure-time option for MsgStack
  CMakeLists.txt
  autoconf_build_defines.hxx.in
  cmake_build_defines.hxx.in
  configure
  configure.ac
  include/bout/build_config.hxx
  include/msg_stack.hxx
  src/bout++.cxx
  src/sys/msg_stack.cxx
  tests/unit/sys/test_msg_stack.cxx
Labels: build-system
