Repository boutproject/BOUT-dev, pull requests merged in 2021-02, with the labels that each got.

#2192 UUID for run_id
  CMakeLists.txt
  autoconf_build_defines.hxx.in
  cmake/FindLibuuid.cmake
  cmake_build_defines.hxx.in
  configure
  configure.ac
  include/bout/build_config.hxx
  include/bout/solver.hxx
  include/bout/sys/uuid.h
  src/solver/solver.cxx
  tests/integrated/test-restart-io/runtest
  tests/integrated/test-squash/runtest
Labels: feature

#2220 Docs: fix escaping
  manual/Makefile
  tools/pylib/_boutcore_build/boutcore.pyx.in
  tools/pylib/_boutcore_build/setup.py.in
Labels: PythonInterface, bugfix, documentation

#2149 Generate random run ID, track restarts
  .github/workflows/clang-tidy-review.yml
  CMakeLists.txt
  autoconf_build_defines.hxx.in
  cmake/FindLibuuid.cmake
  cmake_build_defines.hxx.in
  configure
  configure.ac
  include/bout/build_config.hxx
  include/bout/solver.hxx
  include/bout/sys/uuid.h
  src/solver/solver.cxx
  tests/integrated/test-restart-io/runtest
  tests/integrated/test-squash/runtest
  tests/unit/solver/test_solver.cxx
Labels: backport candidiate

#2223 Only use save_repeat_run_id for dump files
  src/solver/solver.cxx
Labels: bugfix

#2224 Generate random run ID, track restarts (4.4)
  .github/workflows/clang-tidy-review.yml
  CMakeLists.txt
  cmake/FindLibuuid.cmake
  configure
  configure.ac
  include/bout/solver.hxx
  include/bout/sys/uuid.h
  include/datafile.hxx
  src/physics/physicsmodel.cxx
  src/solver/solver.cxx
  tests/integrated/test-io_hdf5/runtest
  tests/integrated/test-restart-io/runtest
  tests/integrated/test-restart-io_hdf5/runtest
  tests/integrated/test-squash/runtest
  tests/unit/solver/test_solver.cxx
Labels: feature

#2237 Fix LaplacePetsc3dAmg
  include/bout/petsc_interface.hxx
  include/bout/region.hxx
  src/invert/laplace/impls/petsc3damg/petsc3damg.cxx
  src/invert/laplace/impls/petsc3damg/petsc3damg.hxx
  src/mesh/interpolation/hermite_spline_z.cxx
  src/mesh/interpolation/interpolation_z.cxx
  tests/integrated/test-laplace-petsc3d/data_circular_core-sol/BOUT.inp
  tests/integrated/test-laplace-petsc3d/data_circular_core/BOUT.inp
Labels: bugfix

#2234 ny_inner label misleading in topology schematic
  manual/sphinx/figs/topology_cross_section.pdf
  manual/sphinx/figs/topology_cross_section.png
  manual/sphinx/figs/topology_cross_section.svg
Labels: documentation

#2230 Save provenance tracking info from grid file
  manual/sphinx/user_docs/output_and_post.rst
  src/mesh/impls/bout/boutmesh.cxx
  src/mesh/impls/bout/boutmesh.hxx
Labels: backport candidiate, documentation, feature, small-change

#2231 Save provenance tracking info from grid file (4.4)
  manual/sphinx/user_docs/output_and_post.rst
  src/mesh/impls/bout/boutmesh.cxx
  src/mesh/impls/bout/boutmesh.hxx
Labels: documentation, feature
