Repository boutproject/BOUT-dev, pull requests merged in 2021-09, with the labels that each got.

#2412 Note in manual that pip and conda can get the most recent cmake
  manual/sphinx/user_docs/installing.rst
Labels: documentation

#2418 Fix BOUT_OVERRIDE_DEFAULT_OPTION() (next)
  include/options.hxx
  include/utils.hxx
  src/sys/options.cxx
  tests/integrated/.gitignore
  tests/integrated/CMakeLists.txt
  tests/integrated/test-bout-override-default-option/CMakeLists.txt
  tests/integrated/test-bout-override-default-option/makefile
  tests/integrated/test-bout-override-default-option/runtest
  tests/integrated/test-bout-override-default-option/test-bout-override-default-option.cxx
Labels: bugfix

#2417 Fix BOUT_OVERRIDE_DEFAULT_OPTION()
  include/options.hxx
  include/utils.hxx
  tests/integrated/.gitignore
  tests/integrated/CMakeLists.txt
  tests/integrated/test-bout-override-default-option/CMakeLists.txt
  tests/integrated/test-bout-override-default-option/makefile
  tests/integrated/test-bout-override-default-option/runtest
  tests/integrated/test-bout-override-default-option/test-bout-override-default-option.cxx
Labels: bugfix

#2421 Add notes on installing SUNDIALS (next)
  manual/sphinx/user_docs/advanced_install.rst
Labels: documentation

#2426 Starting new CoordinatesAccessor design
  CMakeLists.txt
  include/bout/coordinate_field_accessor.hxx
  include/bout/coordinates_accessor.hxx
  include/bout/field_accessor.hxx
  include/bout/single_index_ops.hxx
  src/mesh/coordinates_accessor.cxx
  src/mesh/makefile
  tests/unit/CMakeLists.txt
  tests/unit/include/bout/test_single_index_ops.cxx
  tests/unit/mesh/test_coordinates_accessor.cxx
  tests/unit/test_extras.hxx
Labels: work in progress

#2427 Merge Array with/without Umpire
  CMakeLists.txt
  examples/blob2d-outerloop/blob2d.cxx
  examples/elm-pb-outerloop/elm_pb_outerloop.cxx
  examples/hasegawa-wakatani-3d/hw.cxx
  include/bout/array.hxx
  include/bout/region.hxx
  manual/sphinx/user_docs/gpu_support.rst
Labels: work in progress

#2433 Fix permission of shared objects
  make.config.in
Labels: bugfix, build-system, small-change
