Repository boutproject/BOUT-dev, pull requests merged in 2021-04, with the labels that each got.

#2272 Fix segfault when creating LaplaceXZ without passing Options
  include/bout/invert/laplacexz.hxx
Labels: bugfix

#2275 Next CMake fixes
  bout++Config.cmake.in
  cmake/BOUT++functions.cmake
  cmake/FindnetCDFCxx.cmake
Labels: bugfix, build-system

#2280 Equation numbers in manual
  manual/sphinx/_static/css/custom.css
  manual/sphinx/conf.py
  manual/sphinx/developer_docs/data_types.rst
  manual/sphinx/user_docs/bout_options.rst
  manual/sphinx/user_docs/coordinates.rst
  manual/sphinx/user_docs/differential_operators.rst
  manual/sphinx/user_docs/installing.rst
  manual/sphinx/user_docs/nonlocal.rst
  manual/sphinx/user_docs/output_and_post.rst
  manual/sphinx/user_docs/time_integration.rst
  manual/sphinx/user_docs/variable_init.rst
Labels: documentation

#2282 Make conversion of Option to bool stricter
  CHANGELOG.md
  src/sys/options.cxx
  tests/unit/sys/test_options.cxx
Labels: breaking change
