Repository boutproject/BOUT-dev, pull requests merged in 2021-07, with the labels that each got.

#2371 Fix for compiling without FFTW
  src/invert/fft_fftw.cxx
Labels: bugfix

#2369 Fix documentation for examples/wave-slab
  examples/wave-slab/README.md
  examples/wave-slab/generate.py
Labels: documentation

#2372 Bug fixes for imex-bdf2 solver
  src/solver/impls/imex-bdf2/imex-bdf2.cxx
Labels: bugfix, small-change
