Repository boutproject/BOUT-dev, pull requests merged in 2021-01, with the labels that each got.

#2187 Use MPI_C_BOOL type instead of C++ binding MPI::Bool
  src/invert/laplace/impls/iterative_parallel_tri/iterative_parallel_tri.cxx
Labels: bugfix

#2191 Write descriptions for std::vector<int> and std::string variables
  src/fileio/datafile.cxx
Labels: bugfix, small-change

#2190 Write descriptions for std::vector<int> and std::string variables
  src/fileio/datafile.cxx
Labels: bugfix, small-change

#2189 Fix reading of char* in Ncxx4 (4.4)
  src/fileio/impls/netcdf4/ncxx4.cxx
Labels: bugfix, small-change

#2188 Fix reading of char* in Ncxx4
  src/fileio/impls/netcdf4/ncxx4.cxx
Labels: bugfix, small-change

#2194 Use bout_type="string" for strings in H5Format (4.4)
  src/fileio/impls/hdf5/h5_format.cxx
Labels: small-change

#2193 Use bout_type="string" for strings in H5Format
  src/fileio/impls/hdf5/h5_format.cxx
  tests/integrated/test-io_hdf5/data/benchmark.out.0.hdf5
Labels: backport candidiate, small-change

#2197 Fix test-squash
  .github/workflows/tests.yml
  tests/integrated/test-squash/runtest
Labels: bugfix

#2062 Fix default file format when using legacy netcdf
  CHANGELOG.md
  autoconf_build_defines.hxx.in
  bin/bout-config.in
  bin/bout-v5-macro-upgrader.py
  cmake_build_defines.hxx.in
  configure
  configure.ac
  include/bout/build_config.hxx
  include/options_netcdf.hxx
  src/bout++.cxx
  src/fileio/formatfactory.cxx
  src/fileio/impls/netcdf/nc_format.cxx
  src/fileio/impls/netcdf/nc_format.hxx
  src/fileio/impls/netcdf4/ncxx4.cxx
  src/fileio/impls/netcdf4/ncxx4.hxx
  src/physics/physicsmodel.cxx
  src/sys/options/options_netcdf.cxx
  tests/integrated/test-io/runtest
  tests/integrated/test-options-netcdf/CMakeLists.txt
  tests/integrated/test-options-netcdf/runtest
  tests/integrated/test-solver/test_solver.cxx
  tests/unit/src/test_bout++.cxx
  tests/unit/sys/test_options_netcdf.cxx
  tools/pylib/boutconfig/__init__.py.cin
  tools/pylib/boutconfig/__init__.py.in
Labels: bugfix, small-change

#2201 Minor FCI improvements
  src/mesh/coordinates.cxx
  src/mesh/parallel/fci.cxx
  src/mesh/parallel/fci.hxx
Labels: bugfix

#2203 Next coordinates sigma y
  manual/sphinx/user_docs/coordinates.rst
Labels: documentation

#2211 Update note on zShift in grid-files section of manual
  manual/sphinx/user_docs/input_grids.rst
Labels: documentation
