Repository boutproject/BOUT-dev, pull requests merged in 2023-02, with the labels that each got.

#2637 Workaround PETSc clobbering MPI functions with its macros
  include/bout/invert/laplacexy.hxx
  include/bout/invert/laplacexy2.hxx
  include/bout/petsclib.hxx
  src/invert/laplace/impls/petsc/petsc_laplace.hxx
  src/invert/laplacexy/laplacexy.cxx
  src/invert/laplacexy2/laplacexy2.cxx
  src/solver/impls/imex-bdf2/imex-bdf2.hxx
  src/solver/impls/petsc/petsc.hxx
  src/solver/impls/slepc/slepc.hxx
  src/solver/impls/snes/snes.hxx
Labels: bugfix

#2669 Fix versions after release
  CMakeLists.txt
  manual/RELEASE_HOWTO.md
  tools/pylib/_boutpp_build/backend.py
Labels: small-change

#2664 Improve docs + fix boutpp docs (master)
  manual/sphinx/_apidoc/boutpp.rst
  manual/sphinx/conf.py
  manual/sphinx/developer_docs/file_io.rst
  manual/sphinx/user_docs/advanced_install.rst
  manual/sphinx/user_docs/installing.rst
  tools/pylib/_boutpp_build/boutpp.pyx.jinja
Labels: documentation, bugfix

#2647 fix boutconfig's `has`
  tools/pylib/boutconfig/__init__.py.cin
  tools/pylib/boutconfig/__init__.py.in
Labels: auxiliary-tools, small-change
