Repository boutproject/BOUT-dev, pull requests merged in 2025-01, with the labels that each got.

#3053 Fix finalise in boutpp
  .github/workflows/tests.yml
  tools/pylib/_boutpp_build/boutpp.pyx.jinja
Labels: PythonInterface, bugfix

#3052 Avoid some warnings for 3D Metrics
  src/mesh/boundary_standard.cxx
Labels: small-change

#3051 Minor fixes for the python backend
  tools/pylib/_boutpp_build/backend.py
Labels: small-change

#3061 Make iteration more robust and give more options in LaplaceNaulin
  src/invert/laplace/impls/naulin/naulin_laplace.cxx
  src/invert/laplace/impls/naulin/naulin_laplace.hxx
Labels: feature
